// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: warcraft/types/character-type.proto

package types

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Character struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CharacterId   string                 `protobuf:"bytes,2,opt,name=character_id,json=characterId,proto3" json:"character_id,omitempty"`
	UserId        *string                `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3,oneof" json:"user_id,omitempty"`
	Region        string                 `protobuf:"bytes,4,opt,name=region,proto3" json:"region,omitempty"`
	Realm         string                 `protobuf:"bytes,5,opt,name=realm,proto3" json:"realm,omitempty"`
	Name          string                 `protobuf:"bytes,6,opt,name=name,proto3" json:"name,omitempty"`
	DisplayRealm  *string                `protobuf:"bytes,7,opt,name=display_realm,json=displayRealm,proto3,oneof" json:"display_realm,omitempty"`
	DisplayName   *string                `protobuf:"bytes,8,opt,name=display_name,json=displayName,proto3,oneof" json:"display_name,omitempty"`
	Gender        *string                `protobuf:"bytes,9,opt,name=gender,proto3,oneof" json:"gender,omitempty"`
	Faction       *string                `protobuf:"bytes,10,opt,name=faction,proto3,oneof" json:"faction,omitempty"`
	Race          *string                `protobuf:"bytes,11,opt,name=race,proto3,oneof" json:"race,omitempty"`
	Class         *string                `protobuf:"bytes,12,opt,name=class,proto3,oneof" json:"class,omitempty"`
	Spec          *string                `protobuf:"bytes,13,opt,name=spec,proto3,oneof" json:"spec,omitempty"`
	Level         int64                  `protobuf:"varint,14,opt,name=level,proto3" json:"level,omitempty"`
	ItemLevel     int64                  `protobuf:"varint,15,opt,name=item_level,json=itemLevel,proto3" json:"item_level,omitempty"`
	Guild         *string                `protobuf:"bytes,16,opt,name=guild,proto3,oneof" json:"guild,omitempty"`
	Rank          *int64                 `protobuf:"varint,17,opt,name=rank,proto3,oneof" json:"rank,omitempty"`
	OldGuild      *string                `protobuf:"bytes,18,opt,name=old_guild,json=oldGuild,proto3,oneof" json:"old_guild,omitempty"`
	Inset         *string                `protobuf:"bytes,19,opt,name=inset,proto3,oneof" json:"inset,omitempty"`
	Avatar        *string                `protobuf:"bytes,20,opt,name=avatar,proto3,oneof" json:"avatar,omitempty"`
	Mythic        int64                  `protobuf:"varint,21,opt,name=mythic,proto3" json:"mythic,omitempty"`
	Raid          *string                `protobuf:"bytes,22,opt,name=raid,proto3,oneof" json:"raid,omitempty"`
	LoggedinAt    *string                `protobuf:"bytes,23,opt,name=loggedin_at,json=loggedinAt,proto3,oneof" json:"loggedin_at,omitempty"`
	ActivatedAt   *string                `protobuf:"bytes,24,opt,name=activated_at,json=activatedAt,proto3,oneof" json:"activated_at,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,25,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *string                `protobuf:"bytes,26,opt,name=updated_at,json=updatedAt,proto3,oneof" json:"updated_at,omitempty"`
	DeletedAt     *string                `protobuf:"bytes,27,opt,name=deleted_at,json=deletedAt,proto3,oneof" json:"deleted_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Character) Reset() {
	*x = Character{}
	mi := &file_warcraft_types_character_type_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Character) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Character) ProtoMessage() {}

func (x *Character) ProtoReflect() protoreflect.Message {
	mi := &file_warcraft_types_character_type_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Character.ProtoReflect.Descriptor instead.
func (*Character) Descriptor() ([]byte, []int) {
	return file_warcraft_types_character_type_proto_rawDescGZIP(), []int{0}
}

func (x *Character) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Character) GetCharacterId() string {
	if x != nil {
		return x.CharacterId
	}
	return ""
}

func (x *Character) GetUserId() string {
	if x != nil && x.UserId != nil {
		return *x.UserId
	}
	return ""
}

func (x *Character) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *Character) GetRealm() string {
	if x != nil {
		return x.Realm
	}
	return ""
}

func (x *Character) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Character) GetDisplayRealm() string {
	if x != nil && x.DisplayRealm != nil {
		return *x.DisplayRealm
	}
	return ""
}

func (x *Character) GetDisplayName() string {
	if x != nil && x.DisplayName != nil {
		return *x.DisplayName
	}
	return ""
}

func (x *Character) GetGender() string {
	if x != nil && x.Gender != nil {
		return *x.Gender
	}
	return ""
}

func (x *Character) GetFaction() string {
	if x != nil && x.Faction != nil {
		return *x.Faction
	}
	return ""
}

func (x *Character) GetRace() string {
	if x != nil && x.Race != nil {
		return *x.Race
	}
	return ""
}

func (x *Character) GetClass() string {
	if x != nil && x.Class != nil {
		return *x.Class
	}
	return ""
}

func (x *Character) GetSpec() string {
	if x != nil && x.Spec != nil {
		return *x.Spec
	}
	return ""
}

func (x *Character) GetLevel() int64 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *Character) GetItemLevel() int64 {
	if x != nil {
		return x.ItemLevel
	}
	return 0
}

func (x *Character) GetGuild() string {
	if x != nil && x.Guild != nil {
		return *x.Guild
	}
	return ""
}

func (x *Character) GetRank() int64 {
	if x != nil && x.Rank != nil {
		return *x.Rank
	}
	return 0
}

func (x *Character) GetOldGuild() string {
	if x != nil && x.OldGuild != nil {
		return *x.OldGuild
	}
	return ""
}

func (x *Character) GetInset() string {
	if x != nil && x.Inset != nil {
		return *x.Inset
	}
	return ""
}

func (x *Character) GetAvatar() string {
	if x != nil && x.Avatar != nil {
		return *x.Avatar
	}
	return ""
}

func (x *Character) GetMythic() int64 {
	if x != nil {
		return x.Mythic
	}
	return 0
}

func (x *Character) GetRaid() string {
	if x != nil && x.Raid != nil {
		return *x.Raid
	}
	return ""
}

func (x *Character) GetLoggedinAt() string {
	if x != nil && x.LoggedinAt != nil {
		return *x.LoggedinAt
	}
	return ""
}

func (x *Character) GetActivatedAt() string {
	if x != nil && x.ActivatedAt != nil {
		return *x.ActivatedAt
	}
	return ""
}

func (x *Character) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Character) GetUpdatedAt() string {
	if x != nil && x.UpdatedAt != nil {
		return *x.UpdatedAt
	}
	return ""
}

func (x *Character) GetDeletedAt() string {
	if x != nil && x.DeletedAt != nil {
		return *x.DeletedAt
	}
	return ""
}

var File_warcraft_types_character_type_proto protoreflect.FileDescriptor

const file_warcraft_types_character_type_proto_rawDesc = "" +
	"\n" +
	"#warcraft/types/character-type.proto\x12\x0ewarcraft.types\"\x82\b\n" +
	"\tCharacter\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12!\n" +
	"\fcharacter_id\x18\x02 \x01(\tR\vcharacterId\x12\x1c\n" +
	"\auser_id\x18\x03 \x01(\tH\x00R\x06userId\x88\x01\x01\x12\x16\n" +
	"\x06region\x18\x04 \x01(\tR\x06region\x12\x14\n" +
	"\x05realm\x18\x05 \x01(\tR\x05realm\x12\x12\n" +
	"\x04name\x18\x06 \x01(\tR\x04name\x12(\n" +
	"\rdisplay_realm\x18\a \x01(\tH\x01R\fdisplayRealm\x88\x01\x01\x12&\n" +
	"\fdisplay_name\x18\b \x01(\tH\x02R\vdisplayName\x88\x01\x01\x12\x1b\n" +
	"\x06gender\x18\t \x01(\tH\x03R\x06gender\x88\x01\x01\x12\x1d\n" +
	"\afaction\x18\n" +
	" \x01(\tH\x04R\afaction\x88\x01\x01\x12\x17\n" +
	"\x04race\x18\v \x01(\tH\x05R\x04race\x88\x01\x01\x12\x19\n" +
	"\x05class\x18\f \x01(\tH\x06R\x05class\x88\x01\x01\x12\x17\n" +
	"\x04spec\x18\r \x01(\tH\aR\x04spec\x88\x01\x01\x12\x14\n" +
	"\x05level\x18\x0e \x01(\x03R\x05level\x12\x1d\n" +
	"\n" +
	"item_level\x18\x0f \x01(\x03R\titemLevel\x12\x19\n" +
	"\x05guild\x18\x10 \x01(\tH\bR\x05guild\x88\x01\x01\x12\x17\n" +
	"\x04rank\x18\x11 \x01(\x03H\tR\x04rank\x88\x01\x01\x12 \n" +
	"\told_guild\x18\x12 \x01(\tH\n" +
	"R\boldGuild\x88\x01\x01\x12\x19\n" +
	"\x05inset\x18\x13 \x01(\tH\vR\x05inset\x88\x01\x01\x12\x1b\n" +
	"\x06avatar\x18\x14 \x01(\tH\fR\x06avatar\x88\x01\x01\x12\x16\n" +
	"\x06mythic\x18\x15 \x01(\x03R\x06mythic\x12\x17\n" +
	"\x04raid\x18\x16 \x01(\tH\rR\x04raid\x88\x01\x01\x12$\n" +
	"\vloggedin_at\x18\x17 \x01(\tH\x0eR\n" +
	"loggedinAt\x88\x01\x01\x12&\n" +
	"\factivated_at\x18\x18 \x01(\tH\x0fR\vactivatedAt\x88\x01\x01\x12\x1d\n" +
	"\n" +
	"created_at\x18\x19 \x01(\tR\tcreatedAt\x12\"\n" +
	"\n" +
	"updated_at\x18\x1a \x01(\tH\x10R\tupdatedAt\x88\x01\x01\x12\"\n" +
	"\n" +
	"deleted_at\x18\x1b \x01(\tH\x11R\tdeletedAt\x88\x01\x01B\n" +
	"\n" +
	"\b_user_idB\x10\n" +
	"\x0e_display_realmB\x0f\n" +
	"\r_display_nameB\t\n" +
	"\a_genderB\n" +
	"\n" +
	"\b_factionB\a\n" +
	"\x05_raceB\b\n" +
	"\x06_classB\a\n" +
	"\x05_specB\b\n" +
	"\x06_guildB\a\n" +
	"\x05_rankB\f\n" +
	"\n" +
	"_old_guildB\b\n" +
	"\x06_insetB\t\n" +
	"\a_avatarB\a\n" +
	"\x05_raidB\x0e\n" +
	"\f_loggedin_atB\x0f\n" +
	"\r_activated_atB\r\n" +
	"\v_updated_atB\r\n" +
	"\v_deleted_atBBZ@github.com/ToxicToast/Azkaban-Go/libs/proto/warcraft/types;typesb\x06proto3"

var (
	file_warcraft_types_character_type_proto_rawDescOnce sync.Once
	file_warcraft_types_character_type_proto_rawDescData []byte
)

func file_warcraft_types_character_type_proto_rawDescGZIP() []byte {
	file_warcraft_types_character_type_proto_rawDescOnce.Do(func() {
		file_warcraft_types_character_type_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_warcraft_types_character_type_proto_rawDesc), len(file_warcraft_types_character_type_proto_rawDesc)))
	})
	return file_warcraft_types_character_type_proto_rawDescData
}

var file_warcraft_types_character_type_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_warcraft_types_character_type_proto_goTypes = []any{
	(*Character)(nil), // 0: warcraft.types.Character
}
var file_warcraft_types_character_type_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_warcraft_types_character_type_proto_init() }
func file_warcraft_types_character_type_proto_init() {
	if File_warcraft_types_character_type_proto != nil {
		return
	}
	file_warcraft_types_character_type_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_warcraft_types_character_type_proto_rawDesc), len(file_warcraft_types_character_type_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_warcraft_types_character_type_proto_goTypes,
		DependencyIndexes: file_warcraft_types_character_type_proto_depIdxs,
		MessageInfos:      file_warcraft_types_character_type_proto_msgTypes,
	}.Build()
	File_warcraft_types_character_type_proto = out.File
	file_warcraft_types_character_type_proto_goTypes = nil
	file_warcraft_types_character_type_proto_depIdxs = nil
}
