// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: warcraft/types/guild-responses.proto

package types

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetGuildsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []*Guild               `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGuildsResponse) Reset() {
	*x = GetGuildsResponse{}
	mi := &file_warcraft_types_guild_responses_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGuildsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGuildsResponse) ProtoMessage() {}

func (x *GetGuildsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_warcraft_types_guild_responses_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGuildsResponse.ProtoReflect.Descriptor instead.
func (*GetGuildsResponse) Descriptor() ([]byte, []int) {
	return file_warcraft_types_guild_responses_proto_rawDescGZIP(), []int{0}
}

func (x *GetGuildsResponse) GetData() []*Guild {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *GetGuildsResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

var File_warcraft_types_guild_responses_proto protoreflect.FileDescriptor

const file_warcraft_types_guild_responses_proto_rawDesc = "" +
	"\n" +
	"$warcraft/types/guild-responses.proto\x12\x0ewarcraft.types\x1a\x1fwarcraft/types/guild-type.proto\"T\n" +
	"\x11GetGuildsResponse\x12)\n" +
	"\x04data\x18\x01 \x03(\v2\x15.warcraft.types.GuildR\x04data\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05totalBBZ@github.com/ToxicToast/Azkaban-Go/libs/proto/warcraft/types;typesb\x06proto3"

var (
	file_warcraft_types_guild_responses_proto_rawDescOnce sync.Once
	file_warcraft_types_guild_responses_proto_rawDescData []byte
)

func file_warcraft_types_guild_responses_proto_rawDescGZIP() []byte {
	file_warcraft_types_guild_responses_proto_rawDescOnce.Do(func() {
		file_warcraft_types_guild_responses_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_warcraft_types_guild_responses_proto_rawDesc), len(file_warcraft_types_guild_responses_proto_rawDesc)))
	})
	return file_warcraft_types_guild_responses_proto_rawDescData
}

var file_warcraft_types_guild_responses_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_warcraft_types_guild_responses_proto_goTypes = []any{
	(*GetGuildsResponse)(nil), // 0: warcraft.types.GetGuildsResponse
	(*Guild)(nil),             // 1: warcraft.types.Guild
}
var file_warcraft_types_guild_responses_proto_depIdxs = []int32{
	1, // 0: warcraft.types.GetGuildsResponse.data:type_name -> warcraft.types.Guild
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_warcraft_types_guild_responses_proto_init() }
func file_warcraft_types_guild_responses_proto_init() {
	if File_warcraft_types_guild_responses_proto != nil {
		return
	}
	file_warcraft_types_guild_type_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_warcraft_types_guild_responses_proto_rawDesc), len(file_warcraft_types_guild_responses_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_warcraft_types_guild_responses_proto_goTypes,
		DependencyIndexes: file_warcraft_types_guild_responses_proto_depIdxs,
		MessageInfos:      file_warcraft_types_guild_responses_proto_msgTypes,
	}.Build()
	File_warcraft_types_guild_responses_proto = out.File
	file_warcraft_types_guild_responses_proto_goTypes = nil
	file_warcraft_types_guild_responses_proto_depIdxs = nil
}
