// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: warcraft/character.proto

package warcraft

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Character struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CharacterId   string                 `protobuf:"bytes,2,opt,name=character_id,json=characterId,proto3" json:"character_id,omitempty"`
	UserId        *string                `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3,oneof" json:"user_id,omitempty"`
	Region        string                 `protobuf:"bytes,4,opt,name=region,proto3" json:"region,omitempty"`
	Realm         string                 `protobuf:"bytes,5,opt,name=realm,proto3" json:"realm,omitempty"`
	Name          string                 `protobuf:"bytes,6,opt,name=name,proto3" json:"name,omitempty"`
	DisplayRealm  *string                `protobuf:"bytes,7,opt,name=display_realm,json=displayRealm,proto3,oneof" json:"display_realm,omitempty"`
	DisplayName   *string                `protobuf:"bytes,8,opt,name=display_name,json=displayName,proto3,oneof" json:"display_name,omitempty"`
	Gender        *string                `protobuf:"bytes,9,opt,name=gender,proto3,oneof" json:"gender,omitempty"`
	Faction       *string                `protobuf:"bytes,10,opt,name=faction,proto3,oneof" json:"faction,omitempty"`
	Race          *string                `protobuf:"bytes,11,opt,name=race,proto3,oneof" json:"race,omitempty"`
	Class         *string                `protobuf:"bytes,12,opt,name=class,proto3,oneof" json:"class,omitempty"`
	Spec          *string                `protobuf:"bytes,13,opt,name=spec,proto3,oneof" json:"spec,omitempty"`
	Level         int64                  `protobuf:"varint,14,opt,name=level,proto3" json:"level,omitempty"`
	ItemLevel     int64                  `protobuf:"varint,15,opt,name=item_level,json=itemLevel,proto3" json:"item_level,omitempty"`
	Guild         *string                `protobuf:"bytes,16,opt,name=guild,proto3,oneof" json:"guild,omitempty"`
	Rank          *int64                 `protobuf:"varint,17,opt,name=rank,proto3,oneof" json:"rank,omitempty"`
	OldGuild      *string                `protobuf:"bytes,18,opt,name=old_guild,json=oldGuild,proto3,oneof" json:"old_guild,omitempty"`
	Inset         *string                `protobuf:"bytes,19,opt,name=inset,proto3,oneof" json:"inset,omitempty"`
	Avatar        *string                `protobuf:"bytes,20,opt,name=avatar,proto3,oneof" json:"avatar,omitempty"`
	Mythic        int64                  `protobuf:"varint,21,opt,name=mythic,proto3" json:"mythic,omitempty"`
	Raid          *string                `protobuf:"bytes,22,opt,name=raid,proto3,oneof" json:"raid,omitempty"`
	LoggedinAt    *string                `protobuf:"bytes,23,opt,name=loggedin_at,json=loggedinAt,proto3,oneof" json:"loggedin_at,omitempty"`
	ActivatedAt   *string                `protobuf:"bytes,24,opt,name=activated_at,json=activatedAt,proto3,oneof" json:"activated_at,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,25,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *string                `protobuf:"bytes,26,opt,name=updated_at,json=updatedAt,proto3,oneof" json:"updated_at,omitempty"`
	DeletedAt     *string                `protobuf:"bytes,27,opt,name=deleted_at,json=deletedAt,proto3,oneof" json:"deleted_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Character) Reset() {
	*x = Character{}
	mi := &file_warcraft_character_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Character) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Character) ProtoMessage() {}

func (x *Character) ProtoReflect() protoreflect.Message {
	mi := &file_warcraft_character_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Character.ProtoReflect.Descriptor instead.
func (*Character) Descriptor() ([]byte, []int) {
	return file_warcraft_character_proto_rawDescGZIP(), []int{0}
}

func (x *Character) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Character) GetCharacterId() string {
	if x != nil {
		return x.CharacterId
	}
	return ""
}

func (x *Character) GetUserId() string {
	if x != nil && x.UserId != nil {
		return *x.UserId
	}
	return ""
}

func (x *Character) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *Character) GetRealm() string {
	if x != nil {
		return x.Realm
	}
	return ""
}

func (x *Character) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Character) GetDisplayRealm() string {
	if x != nil && x.DisplayRealm != nil {
		return *x.DisplayRealm
	}
	return ""
}

func (x *Character) GetDisplayName() string {
	if x != nil && x.DisplayName != nil {
		return *x.DisplayName
	}
	return ""
}

func (x *Character) GetGender() string {
	if x != nil && x.Gender != nil {
		return *x.Gender
	}
	return ""
}

func (x *Character) GetFaction() string {
	if x != nil && x.Faction != nil {
		return *x.Faction
	}
	return ""
}

func (x *Character) GetRace() string {
	if x != nil && x.Race != nil {
		return *x.Race
	}
	return ""
}

func (x *Character) GetClass() string {
	if x != nil && x.Class != nil {
		return *x.Class
	}
	return ""
}

func (x *Character) GetSpec() string {
	if x != nil && x.Spec != nil {
		return *x.Spec
	}
	return ""
}

func (x *Character) GetLevel() int64 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *Character) GetItemLevel() int64 {
	if x != nil {
		return x.ItemLevel
	}
	return 0
}

func (x *Character) GetGuild() string {
	if x != nil && x.Guild != nil {
		return *x.Guild
	}
	return ""
}

func (x *Character) GetRank() int64 {
	if x != nil && x.Rank != nil {
		return *x.Rank
	}
	return 0
}

func (x *Character) GetOldGuild() string {
	if x != nil && x.OldGuild != nil {
		return *x.OldGuild
	}
	return ""
}

func (x *Character) GetInset() string {
	if x != nil && x.Inset != nil {
		return *x.Inset
	}
	return ""
}

func (x *Character) GetAvatar() string {
	if x != nil && x.Avatar != nil {
		return *x.Avatar
	}
	return ""
}

func (x *Character) GetMythic() int64 {
	if x != nil {
		return x.Mythic
	}
	return 0
}

func (x *Character) GetRaid() string {
	if x != nil && x.Raid != nil {
		return *x.Raid
	}
	return ""
}

func (x *Character) GetLoggedinAt() string {
	if x != nil && x.LoggedinAt != nil {
		return *x.LoggedinAt
	}
	return ""
}

func (x *Character) GetActivatedAt() string {
	if x != nil && x.ActivatedAt != nil {
		return *x.ActivatedAt
	}
	return ""
}

func (x *Character) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Character) GetUpdatedAt() string {
	if x != nil && x.UpdatedAt != nil {
		return *x.UpdatedAt
	}
	return ""
}

func (x *Character) GetDeletedAt() string {
	if x != nil && x.DeletedAt != nil {
		return *x.DeletedAt
	}
	return ""
}

type GetCharactersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         *int64                 `protobuf:"varint,1,opt,name=limit,proto3,oneof" json:"limit,omitempty"`
	Offset        *int64                 `protobuf:"varint,2,opt,name=offset,proto3,oneof" json:"offset,omitempty"`
	WithDeleted   *bool                  `protobuf:"varint,3,opt,name=with_deleted,json=withDeleted,proto3,oneof" json:"with_deleted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCharactersRequest) Reset() {
	*x = GetCharactersRequest{}
	mi := &file_warcraft_character_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCharactersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCharactersRequest) ProtoMessage() {}

func (x *GetCharactersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_warcraft_character_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCharactersRequest.ProtoReflect.Descriptor instead.
func (*GetCharactersRequest) Descriptor() ([]byte, []int) {
	return file_warcraft_character_proto_rawDescGZIP(), []int{1}
}

func (x *GetCharactersRequest) GetLimit() int64 {
	if x != nil && x.Limit != nil {
		return *x.Limit
	}
	return 0
}

func (x *GetCharactersRequest) GetOffset() int64 {
	if x != nil && x.Offset != nil {
		return *x.Offset
	}
	return 0
}

func (x *GetCharactersRequest) GetWithDeleted() bool {
	if x != nil && x.WithDeleted != nil {
		return *x.WithDeleted
	}
	return false
}

type GetCharactersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []*Character           `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCharactersResponse) Reset() {
	*x = GetCharactersResponse{}
	mi := &file_warcraft_character_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCharactersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCharactersResponse) ProtoMessage() {}

func (x *GetCharactersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_warcraft_character_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCharactersResponse.ProtoReflect.Descriptor instead.
func (*GetCharactersResponse) Descriptor() ([]byte, []int) {
	return file_warcraft_character_proto_rawDescGZIP(), []int{2}
}

func (x *GetCharactersResponse) GetData() []*Character {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *GetCharactersResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type GetCharacterByIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	WithDeleted   *bool                  `protobuf:"varint,2,opt,name=with_deleted,json=withDeleted,proto3,oneof" json:"with_deleted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCharacterByIdRequest) Reset() {
	*x = GetCharacterByIdRequest{}
	mi := &file_warcraft_character_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCharacterByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCharacterByIdRequest) ProtoMessage() {}

func (x *GetCharacterByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_warcraft_character_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCharacterByIdRequest.ProtoReflect.Descriptor instead.
func (*GetCharacterByIdRequest) Descriptor() ([]byte, []int) {
	return file_warcraft_character_proto_rawDescGZIP(), []int{3}
}

func (x *GetCharacterByIdRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetCharacterByIdRequest) GetWithDeleted() bool {
	if x != nil && x.WithDeleted != nil {
		return *x.WithDeleted
	}
	return false
}

type GetCharacterByCharacterIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CharacterId   string                 `protobuf:"bytes,1,opt,name=character_id,json=characterId,proto3" json:"character_id,omitempty"`
	WithDeleted   *bool                  `protobuf:"varint,2,opt,name=with_deleted,json=withDeleted,proto3,oneof" json:"with_deleted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCharacterByCharacterIdRequest) Reset() {
	*x = GetCharacterByCharacterIdRequest{}
	mi := &file_warcraft_character_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCharacterByCharacterIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCharacterByCharacterIdRequest) ProtoMessage() {}

func (x *GetCharacterByCharacterIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_warcraft_character_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCharacterByCharacterIdRequest.ProtoReflect.Descriptor instead.
func (*GetCharacterByCharacterIdRequest) Descriptor() ([]byte, []int) {
	return file_warcraft_character_proto_rawDescGZIP(), []int{4}
}

func (x *GetCharacterByCharacterIdRequest) GetCharacterId() string {
	if x != nil {
		return x.CharacterId
	}
	return ""
}

func (x *GetCharacterByCharacterIdRequest) GetWithDeleted() bool {
	if x != nil && x.WithDeleted != nil {
		return *x.WithDeleted
	}
	return false
}

type GetCharacterByUserIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        *wrapperspb.Int64Value `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	WithDeleted   *bool                  `protobuf:"varint,2,opt,name=with_deleted,json=withDeleted,proto3,oneof" json:"with_deleted,omitempty"`
	Limit         *int64                 `protobuf:"varint,3,opt,name=limit,proto3,oneof" json:"limit,omitempty"`
	Offset        *int64                 `protobuf:"varint,4,opt,name=offset,proto3,oneof" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCharacterByUserIdRequest) Reset() {
	*x = GetCharacterByUserIdRequest{}
	mi := &file_warcraft_character_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCharacterByUserIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCharacterByUserIdRequest) ProtoMessage() {}

func (x *GetCharacterByUserIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_warcraft_character_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCharacterByUserIdRequest.ProtoReflect.Descriptor instead.
func (*GetCharacterByUserIdRequest) Descriptor() ([]byte, []int) {
	return file_warcraft_character_proto_rawDescGZIP(), []int{5}
}

func (x *GetCharacterByUserIdRequest) GetUserId() *wrapperspb.Int64Value {
	if x != nil {
		return x.UserId
	}
	return nil
}

func (x *GetCharacterByUserIdRequest) GetWithDeleted() bool {
	if x != nil && x.WithDeleted != nil {
		return *x.WithDeleted
	}
	return false
}

func (x *GetCharacterByUserIdRequest) GetLimit() int64 {
	if x != nil && x.Limit != nil {
		return *x.Limit
	}
	return 0
}

func (x *GetCharacterByUserIdRequest) GetOffset() int64 {
	if x != nil && x.Offset != nil {
		return *x.Offset
	}
	return 0
}

type GetCharacterByGuildRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Guild         *string                `protobuf:"bytes,1,opt,name=guild,proto3,oneof" json:"guild,omitempty"`
	WithDeleted   *bool                  `protobuf:"varint,2,opt,name=with_deleted,json=withDeleted,proto3,oneof" json:"with_deleted,omitempty"`
	Limit         *int64                 `protobuf:"varint,3,opt,name=limit,proto3,oneof" json:"limit,omitempty"`
	Offset        *int64                 `protobuf:"varint,4,opt,name=offset,proto3,oneof" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCharacterByGuildRequest) Reset() {
	*x = GetCharacterByGuildRequest{}
	mi := &file_warcraft_character_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCharacterByGuildRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCharacterByGuildRequest) ProtoMessage() {}

func (x *GetCharacterByGuildRequest) ProtoReflect() protoreflect.Message {
	mi := &file_warcraft_character_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCharacterByGuildRequest.ProtoReflect.Descriptor instead.
func (*GetCharacterByGuildRequest) Descriptor() ([]byte, []int) {
	return file_warcraft_character_proto_rawDescGZIP(), []int{6}
}

func (x *GetCharacterByGuildRequest) GetGuild() string {
	if x != nil && x.Guild != nil {
		return *x.Guild
	}
	return ""
}

func (x *GetCharacterByGuildRequest) GetWithDeleted() bool {
	if x != nil && x.WithDeleted != nil {
		return *x.WithDeleted
	}
	return false
}

func (x *GetCharacterByGuildRequest) GetLimit() int64 {
	if x != nil && x.Limit != nil {
		return *x.Limit
	}
	return 0
}

func (x *GetCharacterByGuildRequest) GetOffset() int64 {
	if x != nil && x.Offset != nil {
		return *x.Offset
	}
	return 0
}

type CreateCharacterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Region        string                 `protobuf:"bytes,1,opt,name=region,proto3" json:"region,omitempty"`
	Realm         string                 `protobuf:"bytes,2,opt,name=realm,proto3" json:"realm,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCharacterRequest) Reset() {
	*x = CreateCharacterRequest{}
	mi := &file_warcraft_character_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCharacterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCharacterRequest) ProtoMessage() {}

func (x *CreateCharacterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_warcraft_character_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCharacterRequest.ProtoReflect.Descriptor instead.
func (*CreateCharacterRequest) Descriptor() ([]byte, []int) {
	return file_warcraft_character_proto_rawDescGZIP(), []int{7}
}

func (x *CreateCharacterRequest) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *CreateCharacterRequest) GetRealm() string {
	if x != nil {
		return x.Realm
	}
	return ""
}

func (x *CreateCharacterRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type UpdateCharacterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	DisplayRealm  *string                `protobuf:"bytes,2,opt,name=display_realm,json=displayRealm,proto3,oneof" json:"display_realm,omitempty"`
	DisplayName   *string                `protobuf:"bytes,3,opt,name=display_name,json=displayName,proto3,oneof" json:"display_name,omitempty"`
	Gender        *string                `protobuf:"bytes,4,opt,name=gender,proto3,oneof" json:"gender,omitempty"`
	Faction       *string                `protobuf:"bytes,5,opt,name=faction,proto3,oneof" json:"faction,omitempty"`
	Race          *string                `protobuf:"bytes,6,opt,name=race,proto3,oneof" json:"race,omitempty"`
	Class         *string                `protobuf:"bytes,7,opt,name=class,proto3,oneof" json:"class,omitempty"`
	Spec          *string                `protobuf:"bytes,8,opt,name=spec,proto3,oneof" json:"spec,omitempty"`
	Level         *wrapperspb.Int64Value `protobuf:"bytes,9,opt,name=level,proto3" json:"level,omitempty"`
	ItemLevel     *wrapperspb.Int64Value `protobuf:"bytes,10,opt,name=item_level,json=itemLevel,proto3" json:"item_level,omitempty"`
	LoggedinAt    *string                `protobuf:"bytes,11,opt,name=loggedin_at,json=loggedinAt,proto3,oneof" json:"loggedin_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCharacterRequest) Reset() {
	*x = UpdateCharacterRequest{}
	mi := &file_warcraft_character_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCharacterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCharacterRequest) ProtoMessage() {}

func (x *UpdateCharacterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_warcraft_character_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCharacterRequest.ProtoReflect.Descriptor instead.
func (*UpdateCharacterRequest) Descriptor() ([]byte, []int) {
	return file_warcraft_character_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateCharacterRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateCharacterRequest) GetDisplayRealm() string {
	if x != nil && x.DisplayRealm != nil {
		return *x.DisplayRealm
	}
	return ""
}

func (x *UpdateCharacterRequest) GetDisplayName() string {
	if x != nil && x.DisplayName != nil {
		return *x.DisplayName
	}
	return ""
}

func (x *UpdateCharacterRequest) GetGender() string {
	if x != nil && x.Gender != nil {
		return *x.Gender
	}
	return ""
}

func (x *UpdateCharacterRequest) GetFaction() string {
	if x != nil && x.Faction != nil {
		return *x.Faction
	}
	return ""
}

func (x *UpdateCharacterRequest) GetRace() string {
	if x != nil && x.Race != nil {
		return *x.Race
	}
	return ""
}

func (x *UpdateCharacterRequest) GetClass() string {
	if x != nil && x.Class != nil {
		return *x.Class
	}
	return ""
}

func (x *UpdateCharacterRequest) GetSpec() string {
	if x != nil && x.Spec != nil {
		return *x.Spec
	}
	return ""
}

func (x *UpdateCharacterRequest) GetLevel() *wrapperspb.Int64Value {
	if x != nil {
		return x.Level
	}
	return nil
}

func (x *UpdateCharacterRequest) GetItemLevel() *wrapperspb.Int64Value {
	if x != nil {
		return x.ItemLevel
	}
	return nil
}

func (x *UpdateCharacterRequest) GetLoggedinAt() string {
	if x != nil && x.LoggedinAt != nil {
		return *x.LoggedinAt
	}
	return ""
}

type UpdateCharacterGuildRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Guild         *string                `protobuf:"bytes,2,opt,name=guild,proto3,oneof" json:"guild,omitempty"`
	Rank          *wrapperspb.Int64Value `protobuf:"bytes,3,opt,name=rank,proto3" json:"rank,omitempty"`
	OldGuild      *string                `protobuf:"bytes,4,opt,name=old_guild,json=oldGuild,proto3,oneof" json:"old_guild,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCharacterGuildRequest) Reset() {
	*x = UpdateCharacterGuildRequest{}
	mi := &file_warcraft_character_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCharacterGuildRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCharacterGuildRequest) ProtoMessage() {}

func (x *UpdateCharacterGuildRequest) ProtoReflect() protoreflect.Message {
	mi := &file_warcraft_character_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCharacterGuildRequest.ProtoReflect.Descriptor instead.
func (*UpdateCharacterGuildRequest) Descriptor() ([]byte, []int) {
	return file_warcraft_character_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateCharacterGuildRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateCharacterGuildRequest) GetGuild() string {
	if x != nil && x.Guild != nil {
		return *x.Guild
	}
	return ""
}

func (x *UpdateCharacterGuildRequest) GetRank() *wrapperspb.Int64Value {
	if x != nil {
		return x.Rank
	}
	return nil
}

func (x *UpdateCharacterGuildRequest) GetOldGuild() string {
	if x != nil && x.OldGuild != nil {
		return *x.OldGuild
	}
	return ""
}

type UpdateCharacterMythicRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Mythic        *wrapperspb.Int64Value `protobuf:"bytes,2,opt,name=mythic,proto3" json:"mythic,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCharacterMythicRequest) Reset() {
	*x = UpdateCharacterMythicRequest{}
	mi := &file_warcraft_character_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCharacterMythicRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCharacterMythicRequest) ProtoMessage() {}

func (x *UpdateCharacterMythicRequest) ProtoReflect() protoreflect.Message {
	mi := &file_warcraft_character_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCharacterMythicRequest.ProtoReflect.Descriptor instead.
func (*UpdateCharacterMythicRequest) Descriptor() ([]byte, []int) {
	return file_warcraft_character_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateCharacterMythicRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateCharacterMythicRequest) GetMythic() *wrapperspb.Int64Value {
	if x != nil {
		return x.Mythic
	}
	return nil
}

type UpdateCharacterRaidRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Raid          *string                `protobuf:"bytes,2,opt,name=raid,proto3,oneof" json:"raid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCharacterRaidRequest) Reset() {
	*x = UpdateCharacterRaidRequest{}
	mi := &file_warcraft_character_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCharacterRaidRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCharacterRaidRequest) ProtoMessage() {}

func (x *UpdateCharacterRaidRequest) ProtoReflect() protoreflect.Message {
	mi := &file_warcraft_character_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCharacterRaidRequest.ProtoReflect.Descriptor instead.
func (*UpdateCharacterRaidRequest) Descriptor() ([]byte, []int) {
	return file_warcraft_character_proto_rawDescGZIP(), []int{11}
}

func (x *UpdateCharacterRaidRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateCharacterRaidRequest) GetRaid() string {
	if x != nil && x.Raid != nil {
		return *x.Raid
	}
	return ""
}

type UpdateCharacterMediaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Inset         *string                `protobuf:"bytes,2,opt,name=inset,proto3,oneof" json:"inset,omitempty"`
	Avatar        *string                `protobuf:"bytes,3,opt,name=avatar,proto3,oneof" json:"avatar,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCharacterMediaRequest) Reset() {
	*x = UpdateCharacterMediaRequest{}
	mi := &file_warcraft_character_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCharacterMediaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCharacterMediaRequest) ProtoMessage() {}

func (x *UpdateCharacterMediaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_warcraft_character_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCharacterMediaRequest.ProtoReflect.Descriptor instead.
func (*UpdateCharacterMediaRequest) Descriptor() ([]byte, []int) {
	return file_warcraft_character_proto_rawDescGZIP(), []int{12}
}

func (x *UpdateCharacterMediaRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateCharacterMediaRequest) GetInset() string {
	if x != nil && x.Inset != nil {
		return *x.Inset
	}
	return ""
}

func (x *UpdateCharacterMediaRequest) GetAvatar() string {
	if x != nil && x.Avatar != nil {
		return *x.Avatar
	}
	return ""
}

type AssignCharacterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        *wrapperspb.Int64Value `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignCharacterRequest) Reset() {
	*x = AssignCharacterRequest{}
	mi := &file_warcraft_character_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignCharacterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignCharacterRequest) ProtoMessage() {}

func (x *AssignCharacterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_warcraft_character_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignCharacterRequest.ProtoReflect.Descriptor instead.
func (*AssignCharacterRequest) Descriptor() ([]byte, []int) {
	return file_warcraft_character_proto_rawDescGZIP(), []int{13}
}

func (x *AssignCharacterRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AssignCharacterRequest) GetUserId() *wrapperspb.Int64Value {
	if x != nil {
		return x.UserId
	}
	return nil
}

var File_warcraft_character_proto protoreflect.FileDescriptor

const file_warcraft_character_proto_rawDesc = "" +
	"\n" +
	"\x18warcraft/character.proto\x12\bwarcraft\x1a\x1egoogle/protobuf/wrappers.proto\"\x82\b\n" +
	"\tCharacter\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12!\n" +
	"\fcharacter_id\x18\x02 \x01(\tR\vcharacterId\x12\x1c\n" +
	"\auser_id\x18\x03 \x01(\tH\x00R\x06userId\x88\x01\x01\x12\x16\n" +
	"\x06region\x18\x04 \x01(\tR\x06region\x12\x14\n" +
	"\x05realm\x18\x05 \x01(\tR\x05realm\x12\x12\n" +
	"\x04name\x18\x06 \x01(\tR\x04name\x12(\n" +
	"\rdisplay_realm\x18\a \x01(\tH\x01R\fdisplayRealm\x88\x01\x01\x12&\n" +
	"\fdisplay_name\x18\b \x01(\tH\x02R\vdisplayName\x88\x01\x01\x12\x1b\n" +
	"\x06gender\x18\t \x01(\tH\x03R\x06gender\x88\x01\x01\x12\x1d\n" +
	"\afaction\x18\n" +
	" \x01(\tH\x04R\afaction\x88\x01\x01\x12\x17\n" +
	"\x04race\x18\v \x01(\tH\x05R\x04race\x88\x01\x01\x12\x19\n" +
	"\x05class\x18\f \x01(\tH\x06R\x05class\x88\x01\x01\x12\x17\n" +
	"\x04spec\x18\r \x01(\tH\aR\x04spec\x88\x01\x01\x12\x14\n" +
	"\x05level\x18\x0e \x01(\x03R\x05level\x12\x1d\n" +
	"\n" +
	"item_level\x18\x0f \x01(\x03R\titemLevel\x12\x19\n" +
	"\x05guild\x18\x10 \x01(\tH\bR\x05guild\x88\x01\x01\x12\x17\n" +
	"\x04rank\x18\x11 \x01(\x03H\tR\x04rank\x88\x01\x01\x12 \n" +
	"\told_guild\x18\x12 \x01(\tH\n" +
	"R\boldGuild\x88\x01\x01\x12\x19\n" +
	"\x05inset\x18\x13 \x01(\tH\vR\x05inset\x88\x01\x01\x12\x1b\n" +
	"\x06avatar\x18\x14 \x01(\tH\fR\x06avatar\x88\x01\x01\x12\x16\n" +
	"\x06mythic\x18\x15 \x01(\x03R\x06mythic\x12\x17\n" +
	"\x04raid\x18\x16 \x01(\tH\rR\x04raid\x88\x01\x01\x12$\n" +
	"\vloggedin_at\x18\x17 \x01(\tH\x0eR\n" +
	"loggedinAt\x88\x01\x01\x12&\n" +
	"\factivated_at\x18\x18 \x01(\tH\x0fR\vactivatedAt\x88\x01\x01\x12\x1d\n" +
	"\n" +
	"created_at\x18\x19 \x01(\tR\tcreatedAt\x12\"\n" +
	"\n" +
	"updated_at\x18\x1a \x01(\tH\x10R\tupdatedAt\x88\x01\x01\x12\"\n" +
	"\n" +
	"deleted_at\x18\x1b \x01(\tH\x11R\tdeletedAt\x88\x01\x01B\n" +
	"\n" +
	"\b_user_idB\x10\n" +
	"\x0e_display_realmB\x0f\n" +
	"\r_display_nameB\t\n" +
	"\a_genderB\n" +
	"\n" +
	"\b_factionB\a\n" +
	"\x05_raceB\b\n" +
	"\x06_classB\a\n" +
	"\x05_specB\b\n" +
	"\x06_guildB\a\n" +
	"\x05_rankB\f\n" +
	"\n" +
	"_old_guildB\b\n" +
	"\x06_insetB\t\n" +
	"\a_avatarB\a\n" +
	"\x05_raidB\x0e\n" +
	"\f_loggedin_atB\x0f\n" +
	"\r_activated_atB\r\n" +
	"\v_updated_atB\r\n" +
	"\v_deleted_at\"\x9c\x01\n" +
	"\x14GetCharactersRequest\x12\x19\n" +
	"\x05limit\x18\x01 \x01(\x03H\x00R\x05limit\x88\x01\x01\x12\x1b\n" +
	"\x06offset\x18\x02 \x01(\x03H\x01R\x06offset\x88\x01\x01\x12&\n" +
	"\fwith_deleted\x18\x03 \x01(\bH\x02R\vwithDeleted\x88\x01\x01B\b\n" +
	"\x06_limitB\t\n" +
	"\a_offsetB\x0f\n" +
	"\r_with_deleted\"V\n" +
	"\x15GetCharactersResponse\x12'\n" +
	"\x04data\x18\x01 \x03(\v2\x13.warcraft.CharacterR\x04data\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"b\n" +
	"\x17GetCharacterByIdRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12&\n" +
	"\fwith_deleted\x18\x02 \x01(\bH\x00R\vwithDeleted\x88\x01\x01B\x0f\n" +
	"\r_with_deleted\"~\n" +
	" GetCharacterByCharacterIdRequest\x12!\n" +
	"\fcharacter_id\x18\x01 \x01(\tR\vcharacterId\x12&\n" +
	"\fwith_deleted\x18\x02 \x01(\bH\x00R\vwithDeleted\x88\x01\x01B\x0f\n" +
	"\r_with_deleted\"\xd9\x01\n" +
	"\x1bGetCharacterByUserIdRequest\x124\n" +
	"\auser_id\x18\x01 \x01(\v2\x1b.google.protobuf.Int64ValueR\x06userId\x12&\n" +
	"\fwith_deleted\x18\x02 \x01(\bH\x00R\vwithDeleted\x88\x01\x01\x12\x19\n" +
	"\x05limit\x18\x03 \x01(\x03H\x01R\x05limit\x88\x01\x01\x12\x1b\n" +
	"\x06offset\x18\x04 \x01(\x03H\x02R\x06offset\x88\x01\x01B\x0f\n" +
	"\r_with_deletedB\b\n" +
	"\x06_limitB\t\n" +
	"\a_offset\"\xc7\x01\n" +
	"\x1aGetCharacterByGuildRequest\x12\x19\n" +
	"\x05guild\x18\x01 \x01(\tH\x00R\x05guild\x88\x01\x01\x12&\n" +
	"\fwith_deleted\x18\x02 \x01(\bH\x01R\vwithDeleted\x88\x01\x01\x12\x19\n" +
	"\x05limit\x18\x03 \x01(\x03H\x02R\x05limit\x88\x01\x01\x12\x1b\n" +
	"\x06offset\x18\x04 \x01(\x03H\x03R\x06offset\x88\x01\x01B\b\n" +
	"\x06_guildB\x0f\n" +
	"\r_with_deletedB\b\n" +
	"\x06_limitB\t\n" +
	"\a_offset\"Z\n" +
	"\x16CreateCharacterRequest\x12\x16\n" +
	"\x06region\x18\x01 \x01(\tR\x06region\x12\x14\n" +
	"\x05realm\x18\x02 \x01(\tR\x05realm\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\"\xfe\x03\n" +
	"\x16UpdateCharacterRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12(\n" +
	"\rdisplay_realm\x18\x02 \x01(\tH\x00R\fdisplayRealm\x88\x01\x01\x12&\n" +
	"\fdisplay_name\x18\x03 \x01(\tH\x01R\vdisplayName\x88\x01\x01\x12\x1b\n" +
	"\x06gender\x18\x04 \x01(\tH\x02R\x06gender\x88\x01\x01\x12\x1d\n" +
	"\afaction\x18\x05 \x01(\tH\x03R\afaction\x88\x01\x01\x12\x17\n" +
	"\x04race\x18\x06 \x01(\tH\x04R\x04race\x88\x01\x01\x12\x19\n" +
	"\x05class\x18\a \x01(\tH\x05R\x05class\x88\x01\x01\x12\x17\n" +
	"\x04spec\x18\b \x01(\tH\x06R\x04spec\x88\x01\x01\x121\n" +
	"\x05level\x18\t \x01(\v2\x1b.google.protobuf.Int64ValueR\x05level\x12:\n" +
	"\n" +
	"item_level\x18\n" +
	" \x01(\v2\x1b.google.protobuf.Int64ValueR\titemLevel\x12$\n" +
	"\vloggedin_at\x18\v \x01(\tH\aR\n" +
	"loggedinAt\x88\x01\x01B\x10\n" +
	"\x0e_display_realmB\x0f\n" +
	"\r_display_nameB\t\n" +
	"\a_genderB\n" +
	"\n" +
	"\b_factionB\a\n" +
	"\x05_raceB\b\n" +
	"\x06_classB\a\n" +
	"\x05_specB\x0e\n" +
	"\f_loggedin_at\"\xb3\x01\n" +
	"\x1bUpdateCharacterGuildRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x19\n" +
	"\x05guild\x18\x02 \x01(\tH\x00R\x05guild\x88\x01\x01\x12/\n" +
	"\x04rank\x18\x03 \x01(\v2\x1b.google.protobuf.Int64ValueR\x04rank\x12 \n" +
	"\told_guild\x18\x04 \x01(\tH\x01R\boldGuild\x88\x01\x01B\b\n" +
	"\x06_guildB\f\n" +
	"\n" +
	"_old_guild\"c\n" +
	"\x1cUpdateCharacterMythicRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x123\n" +
	"\x06mythic\x18\x02 \x01(\v2\x1b.google.protobuf.Int64ValueR\x06mythic\"N\n" +
	"\x1aUpdateCharacterRaidRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\x04raid\x18\x02 \x01(\tH\x00R\x04raid\x88\x01\x01B\a\n" +
	"\x05_raid\"z\n" +
	"\x1bUpdateCharacterMediaRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x19\n" +
	"\x05inset\x18\x02 \x01(\tH\x00R\x05inset\x88\x01\x01\x12\x1b\n" +
	"\x06avatar\x18\x03 \x01(\tH\x01R\x06avatar\x88\x01\x01B\b\n" +
	"\x06_insetB\t\n" +
	"\a_avatar\"^\n" +
	"\x16AssignCharacterRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x124\n" +
	"\auser_id\x18\x02 \x01(\v2\x1b.google.protobuf.Int64ValueR\x06userId2\x86\b\n" +
	"\x18WarcraftCharacterService\x12P\n" +
	"\rGetCharacters\x12\x1e.warcraft.GetCharactersRequest\x1a\x1f.warcraft.GetCharactersResponse\x12K\n" +
	"\x11GetCharactersById\x12!.warcraft.GetCharacterByIdRequest\x1a\x13.warcraft.Character\x12]\n" +
	"\x1aGetCharactersByCharacterId\x12*.warcraft.GetCharacterByCharacterIdRequest\x1a\x13.warcraft.Character\x12_\n" +
	"\x15GetCharactersByUserId\x12%.warcraft.GetCharacterByUserIdRequest\x1a\x1f.warcraft.GetCharactersResponse\x12]\n" +
	"\x14GetCharactersByGuild\x12$.warcraft.GetCharacterByGuildRequest\x1a\x1f.warcraft.GetCharactersResponse\x12H\n" +
	"\x0fCreateCharacter\x12 .warcraft.CreateCharacterRequest\x1a\x13.warcraft.Character\x12H\n" +
	"\x0fUpdateCharacter\x12 .warcraft.UpdateCharacterRequest\x1a\x13.warcraft.Character\x12R\n" +
	"\x14UpdateCharacterGuild\x12%.warcraft.UpdateCharacterGuildRequest\x1a\x13.warcraft.Character\x12T\n" +
	"\x15UpdateCharacterMythic\x12&.warcraft.UpdateCharacterMythicRequest\x1a\x13.warcraft.Character\x12P\n" +
	"\x13UpdateCharacterRaid\x12$.warcraft.UpdateCharacterRaidRequest\x1a\x13.warcraft.Character\x12R\n" +
	"\x14UpdateCharacterMedia\x12%.warcraft.UpdateCharacterMediaRequest\x1a\x13.warcraft.Character\x12H\n" +
	"\x0fAssignCharacter\x12 .warcraft.AssignCharacterRequest\x1a\x13.warcraft.CharacterB?Z=github.com/ToxicToast/Azkaban-Go/libs/proto/warcraft;warcraftb\x06proto3"

var (
	file_warcraft_character_proto_rawDescOnce sync.Once
	file_warcraft_character_proto_rawDescData []byte
)

func file_warcraft_character_proto_rawDescGZIP() []byte {
	file_warcraft_character_proto_rawDescOnce.Do(func() {
		file_warcraft_character_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_warcraft_character_proto_rawDesc), len(file_warcraft_character_proto_rawDesc)))
	})
	return file_warcraft_character_proto_rawDescData
}

var file_warcraft_character_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_warcraft_character_proto_goTypes = []any{
	(*Character)(nil),                        // 0: warcraft.Character
	(*GetCharactersRequest)(nil),             // 1: warcraft.GetCharactersRequest
	(*GetCharactersResponse)(nil),            // 2: warcraft.GetCharactersResponse
	(*GetCharacterByIdRequest)(nil),          // 3: warcraft.GetCharacterByIdRequest
	(*GetCharacterByCharacterIdRequest)(nil), // 4: warcraft.GetCharacterByCharacterIdRequest
	(*GetCharacterByUserIdRequest)(nil),      // 5: warcraft.GetCharacterByUserIdRequest
	(*GetCharacterByGuildRequest)(nil),       // 6: warcraft.GetCharacterByGuildRequest
	(*CreateCharacterRequest)(nil),           // 7: warcraft.CreateCharacterRequest
	(*UpdateCharacterRequest)(nil),           // 8: warcraft.UpdateCharacterRequest
	(*UpdateCharacterGuildRequest)(nil),      // 9: warcraft.UpdateCharacterGuildRequest
	(*UpdateCharacterMythicRequest)(nil),     // 10: warcraft.UpdateCharacterMythicRequest
	(*UpdateCharacterRaidRequest)(nil),       // 11: warcraft.UpdateCharacterRaidRequest
	(*UpdateCharacterMediaRequest)(nil),      // 12: warcraft.UpdateCharacterMediaRequest
	(*AssignCharacterRequest)(nil),           // 13: warcraft.AssignCharacterRequest
	(*wrapperspb.Int64Value)(nil),            // 14: google.protobuf.Int64Value
}
var file_warcraft_character_proto_depIdxs = []int32{
	0,  // 0: warcraft.GetCharactersResponse.data:type_name -> warcraft.Character
	14, // 1: warcraft.GetCharacterByUserIdRequest.user_id:type_name -> google.protobuf.Int64Value
	14, // 2: warcraft.UpdateCharacterRequest.level:type_name -> google.protobuf.Int64Value
	14, // 3: warcraft.UpdateCharacterRequest.item_level:type_name -> google.protobuf.Int64Value
	14, // 4: warcraft.UpdateCharacterGuildRequest.rank:type_name -> google.protobuf.Int64Value
	14, // 5: warcraft.UpdateCharacterMythicRequest.mythic:type_name -> google.protobuf.Int64Value
	14, // 6: warcraft.AssignCharacterRequest.user_id:type_name -> google.protobuf.Int64Value
	1,  // 7: warcraft.WarcraftCharacterService.GetCharacters:input_type -> warcraft.GetCharactersRequest
	3,  // 8: warcraft.WarcraftCharacterService.GetCharactersById:input_type -> warcraft.GetCharacterByIdRequest
	4,  // 9: warcraft.WarcraftCharacterService.GetCharactersByCharacterId:input_type -> warcraft.GetCharacterByCharacterIdRequest
	5,  // 10: warcraft.WarcraftCharacterService.GetCharactersByUserId:input_type -> warcraft.GetCharacterByUserIdRequest
	6,  // 11: warcraft.WarcraftCharacterService.GetCharactersByGuild:input_type -> warcraft.GetCharacterByGuildRequest
	7,  // 12: warcraft.WarcraftCharacterService.CreateCharacter:input_type -> warcraft.CreateCharacterRequest
	8,  // 13: warcraft.WarcraftCharacterService.UpdateCharacter:input_type -> warcraft.UpdateCharacterRequest
	9,  // 14: warcraft.WarcraftCharacterService.UpdateCharacterGuild:input_type -> warcraft.UpdateCharacterGuildRequest
	10, // 15: warcraft.WarcraftCharacterService.UpdateCharacterMythic:input_type -> warcraft.UpdateCharacterMythicRequest
	11, // 16: warcraft.WarcraftCharacterService.UpdateCharacterRaid:input_type -> warcraft.UpdateCharacterRaidRequest
	12, // 17: warcraft.WarcraftCharacterService.UpdateCharacterMedia:input_type -> warcraft.UpdateCharacterMediaRequest
	13, // 18: warcraft.WarcraftCharacterService.AssignCharacter:input_type -> warcraft.AssignCharacterRequest
	2,  // 19: warcraft.WarcraftCharacterService.GetCharacters:output_type -> warcraft.GetCharactersResponse
	0,  // 20: warcraft.WarcraftCharacterService.GetCharactersById:output_type -> warcraft.Character
	0,  // 21: warcraft.WarcraftCharacterService.GetCharactersByCharacterId:output_type -> warcraft.Character
	2,  // 22: warcraft.WarcraftCharacterService.GetCharactersByUserId:output_type -> warcraft.GetCharactersResponse
	2,  // 23: warcraft.WarcraftCharacterService.GetCharactersByGuild:output_type -> warcraft.GetCharactersResponse
	0,  // 24: warcraft.WarcraftCharacterService.CreateCharacter:output_type -> warcraft.Character
	0,  // 25: warcraft.WarcraftCharacterService.UpdateCharacter:output_type -> warcraft.Character
	0,  // 26: warcraft.WarcraftCharacterService.UpdateCharacterGuild:output_type -> warcraft.Character
	0,  // 27: warcraft.WarcraftCharacterService.UpdateCharacterMythic:output_type -> warcraft.Character
	0,  // 28: warcraft.WarcraftCharacterService.UpdateCharacterRaid:output_type -> warcraft.Character
	0,  // 29: warcraft.WarcraftCharacterService.UpdateCharacterMedia:output_type -> warcraft.Character
	0,  // 30: warcraft.WarcraftCharacterService.AssignCharacter:output_type -> warcraft.Character
	19, // [19:31] is the sub-list for method output_type
	7,  // [7:19] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_warcraft_character_proto_init() }
func file_warcraft_character_proto_init() {
	if File_warcraft_character_proto != nil {
		return
	}
	file_warcraft_character_proto_msgTypes[0].OneofWrappers = []any{}
	file_warcraft_character_proto_msgTypes[1].OneofWrappers = []any{}
	file_warcraft_character_proto_msgTypes[3].OneofWrappers = []any{}
	file_warcraft_character_proto_msgTypes[4].OneofWrappers = []any{}
	file_warcraft_character_proto_msgTypes[5].OneofWrappers = []any{}
	file_warcraft_character_proto_msgTypes[6].OneofWrappers = []any{}
	file_warcraft_character_proto_msgTypes[8].OneofWrappers = []any{}
	file_warcraft_character_proto_msgTypes[9].OneofWrappers = []any{}
	file_warcraft_character_proto_msgTypes[11].OneofWrappers = []any{}
	file_warcraft_character_proto_msgTypes[12].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_warcraft_character_proto_rawDesc), len(file_warcraft_character_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_warcraft_character_proto_goTypes,
		DependencyIndexes: file_warcraft_character_proto_depIdxs,
		MessageInfos:      file_warcraft_character_proto_msgTypes,
	}.Build()
	File_warcraft_character_proto = out.File
	file_warcraft_character_proto_goTypes = nil
	file_warcraft_character_proto_depIdxs = nil
}
