// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: warcraft/character.proto

package warcraft

import (
	shared "github.com/ToxicToast/Azkaban-Go/libs/proto/shared"
	types "github.com/ToxicToast/Azkaban-Go/libs/proto/warcraft/types"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_warcraft_character_proto protoreflect.FileDescriptor

const file_warcraft_character_proto_rawDesc = "" +
	"\n" +
	"\x18warcraft/character.proto\x12\bwarcraft\x1a\x13shared/common.proto\x1a#warcraft/types/character-type.proto\x1a(warcraft/types/character-responses.proto\x1a'warcraft/types/character-requests.proto2\x87\x05\n" +
	"\x18WarcraftCharacterService\x12K\n" +
	"\rGetCharacters\x12\x13.shared.ListRequest\x1a%.warcraft.types.GetCharactersResponse\x12C\n" +
	"\x11GetCharactersById\x12\x13.shared.ByIdRequest\x1a\x19.warcraft.types.Character\x12i\n" +
	"\x1aGetCharactersByCharacterId\x120.warcraft.types.GetCharacterByCharacterIdRequest\x1a\x19.warcraft.types.Character\x12W\n" +
	"\x15GetCharactersByUserId\x12\x17.shared.ByUserIdRequest\x1a%.warcraft.types.GetCharactersResponse\x12i\n" +
	"\x14GetCharactersByGuild\x12*.warcraft.types.GetCharacterByGuildRequest\x1a%.warcraft.types.GetCharactersResponse\x12T\n" +
	"\x0fCreateCharacter\x12&.warcraft.types.CreateCharacterRequest\x1a\x19.warcraft.types.Character\x12T\n" +
	"\x0fAssignCharacter\x12&.warcraft.types.AssignCharacterRequest\x1a\x19.warcraft.types.CharacterB?Z=github.com/ToxicToast/Azkaban-Go/libs/proto/warcraft;warcraftb\x06proto3"

var file_warcraft_character_proto_goTypes = []any{
	(*shared.ListRequest)(nil),                     // 0: shared.ListRequest
	(*shared.ByIdRequest)(nil),                     // 1: shared.ByIdRequest
	(*types.GetCharacterByCharacterIdRequest)(nil), // 2: warcraft.types.GetCharacterByCharacterIdRequest
	(*shared.ByUserIdRequest)(nil),                 // 3: shared.ByUserIdRequest
	(*types.GetCharacterByGuildRequest)(nil),       // 4: warcraft.types.GetCharacterByGuildRequest
	(*types.CreateCharacterRequest)(nil),           // 5: warcraft.types.CreateCharacterRequest
	(*types.AssignCharacterRequest)(nil),           // 6: warcraft.types.AssignCharacterRequest
	(*types.GetCharactersResponse)(nil),            // 7: warcraft.types.GetCharactersResponse
	(*types.Character)(nil),                        // 8: warcraft.types.Character
}
var file_warcraft_character_proto_depIdxs = []int32{
	0, // 0: warcraft.WarcraftCharacterService.GetCharacters:input_type -> shared.ListRequest
	1, // 1: warcraft.WarcraftCharacterService.GetCharactersById:input_type -> shared.ByIdRequest
	2, // 2: warcraft.WarcraftCharacterService.GetCharactersByCharacterId:input_type -> warcraft.types.GetCharacterByCharacterIdRequest
	3, // 3: warcraft.WarcraftCharacterService.GetCharactersByUserId:input_type -> shared.ByUserIdRequest
	4, // 4: warcraft.WarcraftCharacterService.GetCharactersByGuild:input_type -> warcraft.types.GetCharacterByGuildRequest
	5, // 5: warcraft.WarcraftCharacterService.CreateCharacter:input_type -> warcraft.types.CreateCharacterRequest
	6, // 6: warcraft.WarcraftCharacterService.AssignCharacter:input_type -> warcraft.types.AssignCharacterRequest
	7, // 7: warcraft.WarcraftCharacterService.GetCharacters:output_type -> warcraft.types.GetCharactersResponse
	8, // 8: warcraft.WarcraftCharacterService.GetCharactersById:output_type -> warcraft.types.Character
	8, // 9: warcraft.WarcraftCharacterService.GetCharactersByCharacterId:output_type -> warcraft.types.Character
	7, // 10: warcraft.WarcraftCharacterService.GetCharactersByUserId:output_type -> warcraft.types.GetCharactersResponse
	7, // 11: warcraft.WarcraftCharacterService.GetCharactersByGuild:output_type -> warcraft.types.GetCharactersResponse
	8, // 12: warcraft.WarcraftCharacterService.CreateCharacter:output_type -> warcraft.types.Character
	8, // 13: warcraft.WarcraftCharacterService.AssignCharacter:output_type -> warcraft.types.Character
	7, // [7:14] is the sub-list for method output_type
	0, // [0:7] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_warcraft_character_proto_init() }
func file_warcraft_character_proto_init() {
	if File_warcraft_character_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_warcraft_character_proto_rawDesc), len(file_warcraft_character_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_warcraft_character_proto_goTypes,
		DependencyIndexes: file_warcraft_character_proto_depIdxs,
	}.Build()
	File_warcraft_character_proto = out.File
	file_warcraft_character_proto_goTypes = nil
	file_warcraft_character_proto_depIdxs = nil
}
