// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: warcraft/cronjob.proto

package warcraft

import (
	cronjobs "github.com/ToxicToast/Azkaban-Go/libs/proto/warcraft/cronjobs"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_warcraft_cronjob_proto protoreflect.FileDescriptor

const file_warcraft_cronjob_proto_rawDesc = "" +
	"\n" +
	"\x16warcraft/cronjob.proto\x12\bwarcraft\x1a&warcraft/cronjobs/cronjob-search.proto\x1a1warcraft/cronjobs/cronjob-character-profile.proto\x1a%warcraft/cronjobs/cronjob-guild.proto\x1a,warcraft/cronjobs/cronjob-guild-roster.proto\x1a%warcraft/cronjobs/cronjob-media.proto\x1a&warcraft/cronjobs/cronjob-mythic.proto2\x90\x03\n" +
	"\x16WarcraftCronjobService\x12H\n" +
	"\x0fSearchCharacter\x12\x19.warcraft.cronjobs.Search\x1a\x1a.warcraft.cronjobs.Profile\x12B\n" +
	"\vSearchMedia\x12\x19.warcraft.cronjobs.Search\x1a\x18.warcraft.cronjobs.Media\x12T\n" +
	"\x14SearchKeystoneRating\x12\x19.warcraft.cronjobs.Search\x1a!.warcraft.cronjobs.KeystoneRating\x12B\n" +
	"\vSearchGuild\x12\x19.warcraft.cronjobs.Search\x1a\x18.warcraft.cronjobs.Guild\x12N\n" +
	"\x11SearchGuildRoster\x12\x19.warcraft.cronjobs.Search\x1a\x1e.warcraft.cronjobs.GuildRosterB?Z=github.com/ToxicToast/Azkaban-Go/libs/proto/warcraft;warcraftb\x06proto3"

var file_warcraft_cronjob_proto_goTypes = []any{
	(*cronjobs.Search)(nil),         // 0: warcraft.cronjobs.Search
	(*cronjobs.Profile)(nil),        // 1: warcraft.cronjobs.Profile
	(*cronjobs.Media)(nil),          // 2: warcraft.cronjobs.Media
	(*cronjobs.KeystoneRating)(nil), // 3: warcraft.cronjobs.KeystoneRating
	(*cronjobs.Guild)(nil),          // 4: warcraft.cronjobs.Guild
	(*cronjobs.GuildRoster)(nil),    // 5: warcraft.cronjobs.GuildRoster
}
var file_warcraft_cronjob_proto_depIdxs = []int32{
	0, // 0: warcraft.WarcraftCronjobService.SearchCharacter:input_type -> warcraft.cronjobs.Search
	0, // 1: warcraft.WarcraftCronjobService.SearchMedia:input_type -> warcraft.cronjobs.Search
	0, // 2: warcraft.WarcraftCronjobService.SearchKeystoneRating:input_type -> warcraft.cronjobs.Search
	0, // 3: warcraft.WarcraftCronjobService.SearchGuild:input_type -> warcraft.cronjobs.Search
	0, // 4: warcraft.WarcraftCronjobService.SearchGuildRoster:input_type -> warcraft.cronjobs.Search
	1, // 5: warcraft.WarcraftCronjobService.SearchCharacter:output_type -> warcraft.cronjobs.Profile
	2, // 6: warcraft.WarcraftCronjobService.SearchMedia:output_type -> warcraft.cronjobs.Media
	3, // 7: warcraft.WarcraftCronjobService.SearchKeystoneRating:output_type -> warcraft.cronjobs.KeystoneRating
	4, // 8: warcraft.WarcraftCronjobService.SearchGuild:output_type -> warcraft.cronjobs.Guild
	5, // 9: warcraft.WarcraftCronjobService.SearchGuildRoster:output_type -> warcraft.cronjobs.GuildRoster
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_warcraft_cronjob_proto_init() }
func file_warcraft_cronjob_proto_init() {
	if File_warcraft_cronjob_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_warcraft_cronjob_proto_rawDesc), len(file_warcraft_cronjob_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_warcraft_cronjob_proto_goTypes,
		DependencyIndexes: file_warcraft_cronjob_proto_depIdxs,
	}.Build()
	File_warcraft_cronjob_proto = out.File
	file_warcraft_cronjob_proto_goTypes = nil
	file_warcraft_cronjob_proto_depIdxs = nil
}
