// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.31.1
// source: warcraft/guild.proto

package warcraft

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	WarcraftGuildService_GetGuilds_FullMethodName = "/warcraft.WarcraftGuildService/GetGuilds"
)

// WarcraftGuildServiceClient is the client API for WarcraftGuildService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WarcraftGuildServiceClient interface {
	GetGuilds(ctx context.Context, in *GetGuildsRequest, opts ...grpc.CallOption) (*GetGuildsResponse, error)
}

type warcraftGuildServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWarcraftGuildServiceClient(cc grpc.ClientConnInterface) WarcraftGuildServiceClient {
	return &warcraftGuildServiceClient{cc}
}

func (c *warcraftGuildServiceClient) GetGuilds(ctx context.Context, in *GetGuildsRequest, opts ...grpc.CallOption) (*GetGuildsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetGuildsResponse)
	err := c.cc.Invoke(ctx, WarcraftGuildService_GetGuilds_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WarcraftGuildServiceServer is the server API for WarcraftGuildService service.
// All implementations must embed UnimplementedWarcraftGuildServiceServer
// for forward compatibility.
type WarcraftGuildServiceServer interface {
	GetGuilds(context.Context, *GetGuildsRequest) (*GetGuildsResponse, error)
	mustEmbedUnimplementedWarcraftGuildServiceServer()
}

// UnimplementedWarcraftGuildServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWarcraftGuildServiceServer struct{}

func (UnimplementedWarcraftGuildServiceServer) GetGuilds(context.Context, *GetGuildsRequest) (*GetGuildsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetGuilds not implemented")
}
func (UnimplementedWarcraftGuildServiceServer) mustEmbedUnimplementedWarcraftGuildServiceServer() {}
func (UnimplementedWarcraftGuildServiceServer) testEmbeddedByValue()                              {}

// UnsafeWarcraftGuildServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WarcraftGuildServiceServer will
// result in compilation errors.
type UnsafeWarcraftGuildServiceServer interface {
	mustEmbedUnimplementedWarcraftGuildServiceServer()
}

func RegisterWarcraftGuildServiceServer(s grpc.ServiceRegistrar, srv WarcraftGuildServiceServer) {
	// If the following call pancis, it indicates UnimplementedWarcraftGuildServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WarcraftGuildService_ServiceDesc, srv)
}

func _WarcraftGuildService_GetGuilds_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGuildsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WarcraftGuildServiceServer).GetGuilds(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WarcraftGuildService_GetGuilds_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WarcraftGuildServiceServer).GetGuilds(ctx, req.(*GetGuildsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// WarcraftGuildService_ServiceDesc is the grpc.ServiceDesc for WarcraftGuildService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WarcraftGuildService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "warcraft.WarcraftGuildService",
	HandlerType: (*WarcraftGuildServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetGuilds",
			Handler:    _WarcraftGuildService_GetGuilds_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "warcraft/guild.proto",
}
