version: "2"

run:
  skip-files:
    - ".*_test.go"

linters:
  enable:
    - gocyclo
    - revive
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$

linters-settings:
  revive:
    exclude-rules:
      - path: _test\.go
        text: "exported"
  staticcheck:
    exclude-rules:
      - path: _test\.go
        text: "SA2002"
      - path: _test\.go
        text: "SA1019"
  govet:
    exclude-rules:
      - path: _test\.go
        text: "testinggoroutine"