// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: warcraft/character/character-requests.proto

package character

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetCharactersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         *int64                 `protobuf:"varint,1,opt,name=limit,proto3,oneof" json:"limit,omitempty"`
	Offset        *int64                 `protobuf:"varint,2,opt,name=offset,proto3,oneof" json:"offset,omitempty"`
	WithDeleted   *bool                  `protobuf:"varint,3,opt,name=with_deleted,json=withDeleted,proto3,oneof" json:"with_deleted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCharactersRequest) Reset() {
	*x = GetCharactersRequest{}
	mi := &file_warcraft_character_character_requests_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCharactersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCharactersRequest) ProtoMessage() {}

func (x *GetCharactersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_warcraft_character_character_requests_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCharactersRequest.ProtoReflect.Descriptor instead.
func (*GetCharactersRequest) Descriptor() ([]byte, []int) {
	return file_warcraft_character_character_requests_proto_rawDescGZIP(), []int{0}
}

func (x *GetCharactersRequest) GetLimit() int64 {
	if x != nil && x.Limit != nil {
		return *x.Limit
	}
	return 0
}

func (x *GetCharactersRequest) GetOffset() int64 {
	if x != nil && x.Offset != nil {
		return *x.Offset
	}
	return 0
}

func (x *GetCharactersRequest) GetWithDeleted() bool {
	if x != nil && x.WithDeleted != nil {
		return *x.WithDeleted
	}
	return false
}

type GetCharacterByIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	WithDeleted   *bool                  `protobuf:"varint,2,opt,name=with_deleted,json=withDeleted,proto3,oneof" json:"with_deleted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCharacterByIdRequest) Reset() {
	*x = GetCharacterByIdRequest{}
	mi := &file_warcraft_character_character_requests_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCharacterByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCharacterByIdRequest) ProtoMessage() {}

func (x *GetCharacterByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_warcraft_character_character_requests_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCharacterByIdRequest.ProtoReflect.Descriptor instead.
func (*GetCharacterByIdRequest) Descriptor() ([]byte, []int) {
	return file_warcraft_character_character_requests_proto_rawDescGZIP(), []int{1}
}

func (x *GetCharacterByIdRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetCharacterByIdRequest) GetWithDeleted() bool {
	if x != nil && x.WithDeleted != nil {
		return *x.WithDeleted
	}
	return false
}

type GetCharacterByUserIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        *wrapperspb.Int64Value `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	WithDeleted   *bool                  `protobuf:"varint,2,opt,name=with_deleted,json=withDeleted,proto3,oneof" json:"with_deleted,omitempty"`
	Limit         *int64                 `protobuf:"varint,3,opt,name=limit,proto3,oneof" json:"limit,omitempty"`
	Offset        *int64                 `protobuf:"varint,4,opt,name=offset,proto3,oneof" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCharacterByUserIdRequest) Reset() {
	*x = GetCharacterByUserIdRequest{}
	mi := &file_warcraft_character_character_requests_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCharacterByUserIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCharacterByUserIdRequest) ProtoMessage() {}

func (x *GetCharacterByUserIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_warcraft_character_character_requests_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCharacterByUserIdRequest.ProtoReflect.Descriptor instead.
func (*GetCharacterByUserIdRequest) Descriptor() ([]byte, []int) {
	return file_warcraft_character_character_requests_proto_rawDescGZIP(), []int{2}
}

func (x *GetCharacterByUserIdRequest) GetUserId() *wrapperspb.Int64Value {
	if x != nil {
		return x.UserId
	}
	return nil
}

func (x *GetCharacterByUserIdRequest) GetWithDeleted() bool {
	if x != nil && x.WithDeleted != nil {
		return *x.WithDeleted
	}
	return false
}

func (x *GetCharacterByUserIdRequest) GetLimit() int64 {
	if x != nil && x.Limit != nil {
		return *x.Limit
	}
	return 0
}

func (x *GetCharacterByUserIdRequest) GetOffset() int64 {
	if x != nil && x.Offset != nil {
		return *x.Offset
	}
	return 0
}

type GetCharacterByCharacterIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CharacterId   string                 `protobuf:"bytes,1,opt,name=character_id,json=characterId,proto3" json:"character_id,omitempty"`
	WithDeleted   *bool                  `protobuf:"varint,2,opt,name=with_deleted,json=withDeleted,proto3,oneof" json:"with_deleted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCharacterByCharacterIdRequest) Reset() {
	*x = GetCharacterByCharacterIdRequest{}
	mi := &file_warcraft_character_character_requests_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCharacterByCharacterIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCharacterByCharacterIdRequest) ProtoMessage() {}

func (x *GetCharacterByCharacterIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_warcraft_character_character_requests_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCharacterByCharacterIdRequest.ProtoReflect.Descriptor instead.
func (*GetCharacterByCharacterIdRequest) Descriptor() ([]byte, []int) {
	return file_warcraft_character_character_requests_proto_rawDescGZIP(), []int{3}
}

func (x *GetCharacterByCharacterIdRequest) GetCharacterId() string {
	if x != nil {
		return x.CharacterId
	}
	return ""
}

func (x *GetCharacterByCharacterIdRequest) GetWithDeleted() bool {
	if x != nil && x.WithDeleted != nil {
		return *x.WithDeleted
	}
	return false
}

type GetCharacterByGuildRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Guild         *string                `protobuf:"bytes,1,opt,name=guild,proto3,oneof" json:"guild,omitempty"`
	WithDeleted   *bool                  `protobuf:"varint,2,opt,name=with_deleted,json=withDeleted,proto3,oneof" json:"with_deleted,omitempty"`
	Limit         *int64                 `protobuf:"varint,3,opt,name=limit,proto3,oneof" json:"limit,omitempty"`
	Offset        *int64                 `protobuf:"varint,4,opt,name=offset,proto3,oneof" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCharacterByGuildRequest) Reset() {
	*x = GetCharacterByGuildRequest{}
	mi := &file_warcraft_character_character_requests_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCharacterByGuildRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCharacterByGuildRequest) ProtoMessage() {}

func (x *GetCharacterByGuildRequest) ProtoReflect() protoreflect.Message {
	mi := &file_warcraft_character_character_requests_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCharacterByGuildRequest.ProtoReflect.Descriptor instead.
func (*GetCharacterByGuildRequest) Descriptor() ([]byte, []int) {
	return file_warcraft_character_character_requests_proto_rawDescGZIP(), []int{4}
}

func (x *GetCharacterByGuildRequest) GetGuild() string {
	if x != nil && x.Guild != nil {
		return *x.Guild
	}
	return ""
}

func (x *GetCharacterByGuildRequest) GetWithDeleted() bool {
	if x != nil && x.WithDeleted != nil {
		return *x.WithDeleted
	}
	return false
}

func (x *GetCharacterByGuildRequest) GetLimit() int64 {
	if x != nil && x.Limit != nil {
		return *x.Limit
	}
	return 0
}

func (x *GetCharacterByGuildRequest) GetOffset() int64 {
	if x != nil && x.Offset != nil {
		return *x.Offset
	}
	return 0
}

type CreateCharacterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Region        string                 `protobuf:"bytes,1,opt,name=region,proto3" json:"region,omitempty"`
	Realm         string                 `protobuf:"bytes,2,opt,name=realm,proto3" json:"realm,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCharacterRequest) Reset() {
	*x = CreateCharacterRequest{}
	mi := &file_warcraft_character_character_requests_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCharacterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCharacterRequest) ProtoMessage() {}

func (x *CreateCharacterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_warcraft_character_character_requests_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCharacterRequest.ProtoReflect.Descriptor instead.
func (*CreateCharacterRequest) Descriptor() ([]byte, []int) {
	return file_warcraft_character_character_requests_proto_rawDescGZIP(), []int{5}
}

func (x *CreateCharacterRequest) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *CreateCharacterRequest) GetRealm() string {
	if x != nil {
		return x.Realm
	}
	return ""
}

func (x *CreateCharacterRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type AssignCharacterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        *wrapperspb.Int64Value `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignCharacterRequest) Reset() {
	*x = AssignCharacterRequest{}
	mi := &file_warcraft_character_character_requests_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignCharacterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignCharacterRequest) ProtoMessage() {}

func (x *AssignCharacterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_warcraft_character_character_requests_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignCharacterRequest.ProtoReflect.Descriptor instead.
func (*AssignCharacterRequest) Descriptor() ([]byte, []int) {
	return file_warcraft_character_character_requests_proto_rawDescGZIP(), []int{6}
}

func (x *AssignCharacterRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AssignCharacterRequest) GetUserId() *wrapperspb.Int64Value {
	if x != nil {
		return x.UserId
	}
	return nil
}

var File_warcraft_character_character_requests_proto protoreflect.FileDescriptor

const file_warcraft_character_character_requests_proto_rawDesc = "" +
	"\n" +
	"+warcraft/character/character-requests.proto\x12\x12warcraft.character\x1a\x1egoogle/protobuf/wrappers.proto\"\x9c\x01\n" +
	"\x14GetCharactersRequest\x12\x19\n" +
	"\x05limit\x18\x01 \x01(\x03H\x00R\x05limit\x88\x01\x01\x12\x1b\n" +
	"\x06offset\x18\x02 \x01(\x03H\x01R\x06offset\x88\x01\x01\x12&\n" +
	"\fwith_deleted\x18\x03 \x01(\bH\x02R\vwithDeleted\x88\x01\x01B\b\n" +
	"\x06_limitB\t\n" +
	"\a_offsetB\x0f\n" +
	"\r_with_deleted\"b\n" +
	"\x17GetCharacterByIdRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12&\n" +
	"\fwith_deleted\x18\x02 \x01(\bH\x00R\vwithDeleted\x88\x01\x01B\x0f\n" +
	"\r_with_deleted\"\xd9\x01\n" +
	"\x1bGetCharacterByUserIdRequest\x124\n" +
	"\auser_id\x18\x01 \x01(\v2\x1b.google.protobuf.Int64ValueR\x06userId\x12&\n" +
	"\fwith_deleted\x18\x02 \x01(\bH\x00R\vwithDeleted\x88\x01\x01\x12\x19\n" +
	"\x05limit\x18\x03 \x01(\x03H\x01R\x05limit\x88\x01\x01\x12\x1b\n" +
	"\x06offset\x18\x04 \x01(\x03H\x02R\x06offset\x88\x01\x01B\x0f\n" +
	"\r_with_deletedB\b\n" +
	"\x06_limitB\t\n" +
	"\a_offset\"~\n" +
	" GetCharacterByCharacterIdRequest\x12!\n" +
	"\fcharacter_id\x18\x01 \x01(\tR\vcharacterId\x12&\n" +
	"\fwith_deleted\x18\x02 \x01(\bH\x00R\vwithDeleted\x88\x01\x01B\x0f\n" +
	"\r_with_deleted\"\xc7\x01\n" +
	"\x1aGetCharacterByGuildRequest\x12\x19\n" +
	"\x05guild\x18\x01 \x01(\tH\x00R\x05guild\x88\x01\x01\x12&\n" +
	"\fwith_deleted\x18\x02 \x01(\bH\x01R\vwithDeleted\x88\x01\x01\x12\x19\n" +
	"\x05limit\x18\x03 \x01(\x03H\x02R\x05limit\x88\x01\x01\x12\x1b\n" +
	"\x06offset\x18\x04 \x01(\x03H\x03R\x06offset\x88\x01\x01B\b\n" +
	"\x06_guildB\x0f\n" +
	"\r_with_deletedB\b\n" +
	"\x06_limitB\t\n" +
	"\a_offset\"Z\n" +
	"\x16CreateCharacterRequest\x12\x16\n" +
	"\x06region\x18\x01 \x01(\tR\x06region\x12\x14\n" +
	"\x05realm\x18\x02 \x01(\tR\x05realm\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\"^\n" +
	"\x16AssignCharacterRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x124\n" +
	"\auser_id\x18\x02 \x01(\v2\x1b.google.protobuf.Int64ValueR\x06userIdBJZHgithub.com/ToxicToast/Azkaban-Go/libs/proto/warcraft/character;characterb\x06proto3"

var (
	file_warcraft_character_character_requests_proto_rawDescOnce sync.Once
	file_warcraft_character_character_requests_proto_rawDescData []byte
)

func file_warcraft_character_character_requests_proto_rawDescGZIP() []byte {
	file_warcraft_character_character_requests_proto_rawDescOnce.Do(func() {
		file_warcraft_character_character_requests_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_warcraft_character_character_requests_proto_rawDesc), len(file_warcraft_character_character_requests_proto_rawDesc)))
	})
	return file_warcraft_character_character_requests_proto_rawDescData
}

var file_warcraft_character_character_requests_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_warcraft_character_character_requests_proto_goTypes = []any{
	(*GetCharactersRequest)(nil),             // 0: warcraft.character.GetCharactersRequest
	(*GetCharacterByIdRequest)(nil),          // 1: warcraft.character.GetCharacterByIdRequest
	(*GetCharacterByUserIdRequest)(nil),      // 2: warcraft.character.GetCharacterByUserIdRequest
	(*GetCharacterByCharacterIdRequest)(nil), // 3: warcraft.character.GetCharacterByCharacterIdRequest
	(*GetCharacterByGuildRequest)(nil),       // 4: warcraft.character.GetCharacterByGuildRequest
	(*CreateCharacterRequest)(nil),           // 5: warcraft.character.CreateCharacterRequest
	(*AssignCharacterRequest)(nil),           // 6: warcraft.character.AssignCharacterRequest
	(*wrapperspb.Int64Value)(nil),            // 7: google.protobuf.Int64Value
}
var file_warcraft_character_character_requests_proto_depIdxs = []int32{
	7, // 0: warcraft.character.GetCharacterByUserIdRequest.user_id:type_name -> google.protobuf.Int64Value
	7, // 1: warcraft.character.AssignCharacterRequest.user_id:type_name -> google.protobuf.Int64Value
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_warcraft_character_character_requests_proto_init() }
func file_warcraft_character_character_requests_proto_init() {
	if File_warcraft_character_character_requests_proto != nil {
		return
	}
	file_warcraft_character_character_requests_proto_msgTypes[0].OneofWrappers = []any{}
	file_warcraft_character_character_requests_proto_msgTypes[1].OneofWrappers = []any{}
	file_warcraft_character_character_requests_proto_msgTypes[2].OneofWrappers = []any{}
	file_warcraft_character_character_requests_proto_msgTypes[3].OneofWrappers = []any{}
	file_warcraft_character_character_requests_proto_msgTypes[4].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_warcraft_character_character_requests_proto_rawDesc), len(file_warcraft_character_character_requests_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_warcraft_character_character_requests_proto_goTypes,
		DependencyIndexes: file_warcraft_character_character_requests_proto_depIdxs,
		MessageInfos:      file_warcraft_character_character_requests_proto_msgTypes,
	}.Build()
	File_warcraft_character_character_requests_proto = out.File
	file_warcraft_character_character_requests_proto_goTypes = nil
	file_warcraft_character_character_requests_proto_depIdxs = nil
}
