// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: warcraft/character/character.proto

package character

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_warcraft_character_character_proto protoreflect.FileDescriptor

const file_warcraft_character_character_proto_rawDesc = "" +
	"\n" +
	"\"warcraft/character/character.proto\x12\x12warcraft.character\x1a'warcraft/character/character-type.proto\x1a,warcraft/character/character-responses.proto\x1a+warcraft/character/character-requests.proto2\xf8\x05\n" +
	"\x18WarcraftCharacterService\x12d\n" +
	"\rGetCharacters\x12(.warcraft.character.GetCharactersRequest\x1a).warcraft.character.GetCharactersResponse\x12_\n" +
	"\x11GetCharactersById\x12+.warcraft.character.GetCharacterByIdRequest\x1a\x1d.warcraft.character.Character\x12q\n" +
	"\x1aGetCharactersByCharacterId\x124.warcraft.character.GetCharacterByCharacterIdRequest\x1a\x1d.warcraft.character.Character\x12s\n" +
	"\x15GetCharactersByUserId\x12/.warcraft.character.GetCharacterByUserIdRequest\x1a).warcraft.character.GetCharactersResponse\x12q\n" +
	"\x14GetCharactersByGuild\x12..warcraft.character.GetCharacterByGuildRequest\x1a).warcraft.character.GetCharactersResponse\x12\\\n" +
	"\x0fCreateCharacter\x12*.warcraft.character.CreateCharacterRequest\x1a\x1d.warcraft.character.Character\x12\\\n" +
	"\x0fAssignCharacter\x12*.warcraft.character.AssignCharacterRequest\x1a\x1d.warcraft.character.CharacterBJZHgithub.com/ToxicToast/Azkaban-Go/libs/proto/warcraft/character;characterb\x06proto3"

var file_warcraft_character_character_proto_goTypes = []any{
	(*GetCharactersRequest)(nil),             // 0: warcraft.character.GetCharactersRequest
	(*GetCharacterByIdRequest)(nil),          // 1: warcraft.character.GetCharacterByIdRequest
	(*GetCharacterByCharacterIdRequest)(nil), // 2: warcraft.character.GetCharacterByCharacterIdRequest
	(*GetCharacterByUserIdRequest)(nil),      // 3: warcraft.character.GetCharacterByUserIdRequest
	(*GetCharacterByGuildRequest)(nil),       // 4: warcraft.character.GetCharacterByGuildRequest
	(*CreateCharacterRequest)(nil),           // 5: warcraft.character.CreateCharacterRequest
	(*AssignCharacterRequest)(nil),           // 6: warcraft.character.AssignCharacterRequest
	(*GetCharactersResponse)(nil),            // 7: warcraft.character.GetCharactersResponse
	(*Character)(nil),                        // 8: warcraft.character.Character
}
var file_warcraft_character_character_proto_depIdxs = []int32{
	0, // 0: warcraft.character.WarcraftCharacterService.GetCharacters:input_type -> warcraft.character.GetCharactersRequest
	1, // 1: warcraft.character.WarcraftCharacterService.GetCharactersById:input_type -> warcraft.character.GetCharacterByIdRequest
	2, // 2: warcraft.character.WarcraftCharacterService.GetCharactersByCharacterId:input_type -> warcraft.character.GetCharacterByCharacterIdRequest
	3, // 3: warcraft.character.WarcraftCharacterService.GetCharactersByUserId:input_type -> warcraft.character.GetCharacterByUserIdRequest
	4, // 4: warcraft.character.WarcraftCharacterService.GetCharactersByGuild:input_type -> warcraft.character.GetCharacterByGuildRequest
	5, // 5: warcraft.character.WarcraftCharacterService.CreateCharacter:input_type -> warcraft.character.CreateCharacterRequest
	6, // 6: warcraft.character.WarcraftCharacterService.AssignCharacter:input_type -> warcraft.character.AssignCharacterRequest
	7, // 7: warcraft.character.WarcraftCharacterService.GetCharacters:output_type -> warcraft.character.GetCharactersResponse
	8, // 8: warcraft.character.WarcraftCharacterService.GetCharactersById:output_type -> warcraft.character.Character
	8, // 9: warcraft.character.WarcraftCharacterService.GetCharactersByCharacterId:output_type -> warcraft.character.Character
	7, // 10: warcraft.character.WarcraftCharacterService.GetCharactersByUserId:output_type -> warcraft.character.GetCharactersResponse
	7, // 11: warcraft.character.WarcraftCharacterService.GetCharactersByGuild:output_type -> warcraft.character.GetCharactersResponse
	8, // 12: warcraft.character.WarcraftCharacterService.CreateCharacter:output_type -> warcraft.character.Character
	8, // 13: warcraft.character.WarcraftCharacterService.AssignCharacter:output_type -> warcraft.character.Character
	7, // [7:14] is the sub-list for method output_type
	0, // [0:7] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_warcraft_character_character_proto_init() }
func file_warcraft_character_character_proto_init() {
	if File_warcraft_character_character_proto != nil {
		return
	}
	file_warcraft_character_character_type_proto_init()
	file_warcraft_character_character_responses_proto_init()
	file_warcraft_character_character_requests_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_warcraft_character_character_proto_rawDesc), len(file_warcraft_character_character_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_warcraft_character_character_proto_goTypes,
		DependencyIndexes: file_warcraft_character_character_proto_depIdxs,
	}.Build()
	File_warcraft_character_character_proto = out.File
	file_warcraft_character_character_proto_goTypes = nil
	file_warcraft_character_character_proto_depIdxs = nil
}
