// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: warcraft/cronjobs/cronjob-guild-roster.proto

package cronjobs

import (
	warcraft "github.com/ToxicToast/Azkaban-Go/libs/proto/warcraft"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 📌 Class / Race Referenz
type ReferenceWithId struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           *warcraft.Key          `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Id            int64                  `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReferenceWithId) Reset() {
	*x = ReferenceWithId{}
	mi := &file_warcraft_cronjobs_cronjob_guild_roster_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReferenceWithId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReferenceWithId) ProtoMessage() {}

func (x *ReferenceWithId) ProtoReflect() protoreflect.Message {
	mi := &file_warcraft_cronjobs_cronjob_guild_roster_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReferenceWithId.ProtoReflect.Descriptor instead.
func (*ReferenceWithId) Descriptor() ([]byte, []int) {
	return file_warcraft_cronjobs_cronjob_guild_roster_proto_rawDescGZIP(), []int{0}
}

func (x *ReferenceWithId) GetKey() *warcraft.Key {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *ReferenceWithId) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// 📌 Charakterdetails in Member
type Character struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           *warcraft.Key          `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Id            int64                  `protobuf:"varint,3,opt,name=id,proto3" json:"id,omitempty"`
	Realm         *warcraft.Realm        `protobuf:"bytes,4,opt,name=realm,proto3" json:"realm,omitempty"`
	Level         int32                  `protobuf:"varint,5,opt,name=level,proto3" json:"level,omitempty"`
	PlayableClass *ReferenceWithId       `protobuf:"bytes,6,opt,name=playable_class,json=playableClass,proto3" json:"playable_class,omitempty"`
	PlayableRace  *ReferenceWithId       `protobuf:"bytes,7,opt,name=playable_race,json=playableRace,proto3" json:"playable_race,omitempty"`
	Faction       *warcraft.Faction      `protobuf:"bytes,8,opt,name=faction,proto3" json:"faction,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Character) Reset() {
	*x = Character{}
	mi := &file_warcraft_cronjobs_cronjob_guild_roster_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Character) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Character) ProtoMessage() {}

func (x *Character) ProtoReflect() protoreflect.Message {
	mi := &file_warcraft_cronjobs_cronjob_guild_roster_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Character.ProtoReflect.Descriptor instead.
func (*Character) Descriptor() ([]byte, []int) {
	return file_warcraft_cronjobs_cronjob_guild_roster_proto_rawDescGZIP(), []int{1}
}

func (x *Character) GetKey() *warcraft.Key {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *Character) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Character) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Character) GetRealm() *warcraft.Realm {
	if x != nil {
		return x.Realm
	}
	return nil
}

func (x *Character) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *Character) GetPlayableClass() *ReferenceWithId {
	if x != nil {
		return x.PlayableClass
	}
	return nil
}

func (x *Character) GetPlayableRace() *ReferenceWithId {
	if x != nil {
		return x.PlayableRace
	}
	return nil
}

func (x *Character) GetFaction() *warcraft.Faction {
	if x != nil {
		return x.Faction
	}
	return nil
}

// 📌 Einzelner Member (Charakter + Rang)
type GuildMember struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Character     *Character             `protobuf:"bytes,1,opt,name=character,proto3" json:"character,omitempty"`
	Rank          int32                  `protobuf:"varint,2,opt,name=rank,proto3" json:"rank,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GuildMember) Reset() {
	*x = GuildMember{}
	mi := &file_warcraft_cronjobs_cronjob_guild_roster_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GuildMember) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GuildMember) ProtoMessage() {}

func (x *GuildMember) ProtoReflect() protoreflect.Message {
	mi := &file_warcraft_cronjobs_cronjob_guild_roster_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GuildMember.ProtoReflect.Descriptor instead.
func (*GuildMember) Descriptor() ([]byte, []int) {
	return file_warcraft_cronjobs_cronjob_guild_roster_proto_rawDescGZIP(), []int{2}
}

func (x *GuildMember) GetCharacter() *Character {
	if x != nil {
		return x.Character
	}
	return nil
}

func (x *GuildMember) GetRank() int32 {
	if x != nil {
		return x.Rank
	}
	return 0
}

// 📌 Gilde
type GuildRoster struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	XLinks        *warcraft.Self         `protobuf:"bytes,1,opt,name=_links,json=Links,proto3" json:"_links,omitempty"`
	Guild         *GuildRoster_GuildData `protobuf:"bytes,2,opt,name=guild,proto3" json:"guild,omitempty"`
	Members       []*GuildMember         `protobuf:"bytes,3,rep,name=members,proto3" json:"members,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GuildRoster) Reset() {
	*x = GuildRoster{}
	mi := &file_warcraft_cronjobs_cronjob_guild_roster_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GuildRoster) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GuildRoster) ProtoMessage() {}

func (x *GuildRoster) ProtoReflect() protoreflect.Message {
	mi := &file_warcraft_cronjobs_cronjob_guild_roster_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GuildRoster.ProtoReflect.Descriptor instead.
func (*GuildRoster) Descriptor() ([]byte, []int) {
	return file_warcraft_cronjobs_cronjob_guild_roster_proto_rawDescGZIP(), []int{3}
}

func (x *GuildRoster) GetXLinks() *warcraft.Self {
	if x != nil {
		return x.XLinks
	}
	return nil
}

func (x *GuildRoster) GetGuild() *GuildRoster_GuildData {
	if x != nil {
		return x.Guild
	}
	return nil
}

func (x *GuildRoster) GetMembers() []*GuildMember {
	if x != nil {
		return x.Members
	}
	return nil
}

type GuildRoster_GuildData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           *warcraft.Key          `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Id            int64                  `protobuf:"varint,3,opt,name=id,proto3" json:"id,omitempty"`
	Realm         *warcraft.Realm        `protobuf:"bytes,4,opt,name=realm,proto3" json:"realm,omitempty"`
	Faction       *warcraft.Faction      `protobuf:"bytes,5,opt,name=faction,proto3" json:"faction,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GuildRoster_GuildData) Reset() {
	*x = GuildRoster_GuildData{}
	mi := &file_warcraft_cronjobs_cronjob_guild_roster_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GuildRoster_GuildData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GuildRoster_GuildData) ProtoMessage() {}

func (x *GuildRoster_GuildData) ProtoReflect() protoreflect.Message {
	mi := &file_warcraft_cronjobs_cronjob_guild_roster_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GuildRoster_GuildData.ProtoReflect.Descriptor instead.
func (*GuildRoster_GuildData) Descriptor() ([]byte, []int) {
	return file_warcraft_cronjobs_cronjob_guild_roster_proto_rawDescGZIP(), []int{3, 0}
}

func (x *GuildRoster_GuildData) GetKey() *warcraft.Key {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *GuildRoster_GuildData) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GuildRoster_GuildData) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GuildRoster_GuildData) GetRealm() *warcraft.Realm {
	if x != nil {
		return x.Realm
	}
	return nil
}

func (x *GuildRoster_GuildData) GetFaction() *warcraft.Faction {
	if x != nil {
		return x.Faction
	}
	return nil
}

var File_warcraft_cronjobs_cronjob_guild_roster_proto protoreflect.FileDescriptor

const file_warcraft_cronjobs_cronjob_guild_roster_proto_rawDesc = "" +
	"\n" +
	",warcraft/cronjobs/cronjob-guild-roster.proto\x12\x11warcraft.cronjobs\x1a\x15warcraft/common.proto\"B\n" +
	"\x0fReferenceWithId\x12\x1f\n" +
	"\x03key\x18\x01 \x01(\v2\r.warcraft.KeyR\x03key\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\x03R\x02id\"\xce\x02\n" +
	"\tCharacter\x12\x1f\n" +
	"\x03key\x18\x01 \x01(\v2\r.warcraft.KeyR\x03key\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x0e\n" +
	"\x02id\x18\x03 \x01(\x03R\x02id\x12%\n" +
	"\x05realm\x18\x04 \x01(\v2\x0f.warcraft.RealmR\x05realm\x12\x14\n" +
	"\x05level\x18\x05 \x01(\x05R\x05level\x12I\n" +
	"\x0eplayable_class\x18\x06 \x01(\v2\".warcraft.cronjobs.ReferenceWithIdR\rplayableClass\x12G\n" +
	"\rplayable_race\x18\a \x01(\v2\".warcraft.cronjobs.ReferenceWithIdR\fplayableRace\x12+\n" +
	"\afaction\x18\b \x01(\v2\x11.warcraft.FactionR\afaction\"]\n" +
	"\vGuildMember\x12:\n" +
	"\tcharacter\x18\x01 \x01(\v2\x1c.warcraft.cronjobs.CharacterR\tcharacter\x12\x12\n" +
	"\x04rank\x18\x02 \x01(\x05R\x04rank\"\xd5\x02\n" +
	"\vGuildRoster\x12%\n" +
	"\x06_links\x18\x01 \x01(\v2\x0e.warcraft.SelfR\x05Links\x12>\n" +
	"\x05guild\x18\x02 \x01(\v2(.warcraft.cronjobs.GuildRoster.GuildDataR\x05guild\x128\n" +
	"\amembers\x18\x03 \x03(\v2\x1e.warcraft.cronjobs.GuildMemberR\amembers\x1a\xa4\x01\n" +
	"\tGuildData\x12\x1f\n" +
	"\x03key\x18\x01 \x01(\v2\r.warcraft.KeyR\x03key\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x0e\n" +
	"\x02id\x18\x03 \x01(\x03R\x02id\x12%\n" +
	"\x05realm\x18\x04 \x01(\v2\x0f.warcraft.RealmR\x05realm\x12+\n" +
	"\afaction\x18\x05 \x01(\v2\x11.warcraft.FactionR\afactionBHZFgithub.com/ToxicToast/Azkaban-Go/libs/proto/warcraft/cronjobs;cronjobsb\x06proto3"

var (
	file_warcraft_cronjobs_cronjob_guild_roster_proto_rawDescOnce sync.Once
	file_warcraft_cronjobs_cronjob_guild_roster_proto_rawDescData []byte
)

func file_warcraft_cronjobs_cronjob_guild_roster_proto_rawDescGZIP() []byte {
	file_warcraft_cronjobs_cronjob_guild_roster_proto_rawDescOnce.Do(func() {
		file_warcraft_cronjobs_cronjob_guild_roster_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_warcraft_cronjobs_cronjob_guild_roster_proto_rawDesc), len(file_warcraft_cronjobs_cronjob_guild_roster_proto_rawDesc)))
	})
	return file_warcraft_cronjobs_cronjob_guild_roster_proto_rawDescData
}

var file_warcraft_cronjobs_cronjob_guild_roster_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_warcraft_cronjobs_cronjob_guild_roster_proto_goTypes = []any{
	(*ReferenceWithId)(nil),       // 0: warcraft.cronjobs.ReferenceWithId
	(*Character)(nil),             // 1: warcraft.cronjobs.Character
	(*GuildMember)(nil),           // 2: warcraft.cronjobs.GuildMember
	(*GuildRoster)(nil),           // 3: warcraft.cronjobs.GuildRoster
	(*GuildRoster_GuildData)(nil), // 4: warcraft.cronjobs.GuildRoster.GuildData
	(*warcraft.Key)(nil),          // 5: warcraft.Key
	(*warcraft.Realm)(nil),        // 6: warcraft.Realm
	(*warcraft.Faction)(nil),      // 7: warcraft.Faction
	(*warcraft.Self)(nil),         // 8: warcraft.Self
}
var file_warcraft_cronjobs_cronjob_guild_roster_proto_depIdxs = []int32{
	5,  // 0: warcraft.cronjobs.ReferenceWithId.key:type_name -> warcraft.Key
	5,  // 1: warcraft.cronjobs.Character.key:type_name -> warcraft.Key
	6,  // 2: warcraft.cronjobs.Character.realm:type_name -> warcraft.Realm
	0,  // 3: warcraft.cronjobs.Character.playable_class:type_name -> warcraft.cronjobs.ReferenceWithId
	0,  // 4: warcraft.cronjobs.Character.playable_race:type_name -> warcraft.cronjobs.ReferenceWithId
	7,  // 5: warcraft.cronjobs.Character.faction:type_name -> warcraft.Faction
	1,  // 6: warcraft.cronjobs.GuildMember.character:type_name -> warcraft.cronjobs.Character
	8,  // 7: warcraft.cronjobs.GuildRoster._links:type_name -> warcraft.Self
	4,  // 8: warcraft.cronjobs.GuildRoster.guild:type_name -> warcraft.cronjobs.GuildRoster.GuildData
	2,  // 9: warcraft.cronjobs.GuildRoster.members:type_name -> warcraft.cronjobs.GuildMember
	5,  // 10: warcraft.cronjobs.GuildRoster.GuildData.key:type_name -> warcraft.Key
	6,  // 11: warcraft.cronjobs.GuildRoster.GuildData.realm:type_name -> warcraft.Realm
	7,  // 12: warcraft.cronjobs.GuildRoster.GuildData.faction:type_name -> warcraft.Faction
	13, // [13:13] is the sub-list for method output_type
	13, // [13:13] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_warcraft_cronjobs_cronjob_guild_roster_proto_init() }
func file_warcraft_cronjobs_cronjob_guild_roster_proto_init() {
	if File_warcraft_cronjobs_cronjob_guild_roster_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_warcraft_cronjobs_cronjob_guild_roster_proto_rawDesc), len(file_warcraft_cronjobs_cronjob_guild_roster_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_warcraft_cronjobs_cronjob_guild_roster_proto_goTypes,
		DependencyIndexes: file_warcraft_cronjobs_cronjob_guild_roster_proto_depIdxs,
		MessageInfos:      file_warcraft_cronjobs_cronjob_guild_roster_proto_msgTypes,
	}.Build()
	File_warcraft_cronjobs_cronjob_guild_roster_proto = out.File
	file_warcraft_cronjobs_cronjob_guild_roster_proto_goTypes = nil
	file_warcraft_cronjobs_cronjob_guild_roster_proto_depIdxs = nil
}
