// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: warcraft/cronjobs/cronjob-mythic.proto

package cronjobs

import (
	warcraft "github.com/ToxicToast/Azkaban-Go/libs/proto/warcraft"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 📌 Perioden-Info (z. B. Season oder aktuelle ID)
type PeriodRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           *warcraft.Key          `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Id            int64                  `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeriodRef) Reset() {
	*x = PeriodRef{}
	mi := &file_warcraft_cronjobs_cronjob_mythic_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeriodRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeriodRef) ProtoMessage() {}

func (x *PeriodRef) ProtoReflect() protoreflect.Message {
	mi := &file_warcraft_cronjobs_cronjob_mythic_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeriodRef.ProtoReflect.Descriptor instead.
func (*PeriodRef) Descriptor() ([]byte, []int) {
	return file_warcraft_cronjobs_cronjob_mythic_proto_rawDescGZIP(), []int{0}
}

func (x *PeriodRef) GetKey() *warcraft.Key {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *PeriodRef) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// 📌 Aktuelle Rating-Daten
type CurrentMythicRating struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Color         *warcraft.Color        `protobuf:"bytes,1,opt,name=color,proto3" json:"color,omitempty"`
	Rating        float32                `protobuf:"fixed32,2,opt,name=rating,proto3" json:"rating,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CurrentMythicRating) Reset() {
	*x = CurrentMythicRating{}
	mi := &file_warcraft_cronjobs_cronjob_mythic_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CurrentMythicRating) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CurrentMythicRating) ProtoMessage() {}

func (x *CurrentMythicRating) ProtoReflect() protoreflect.Message {
	mi := &file_warcraft_cronjobs_cronjob_mythic_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CurrentMythicRating.ProtoReflect.Descriptor instead.
func (*CurrentMythicRating) Descriptor() ([]byte, []int) {
	return file_warcraft_cronjobs_cronjob_mythic_proto_rawDescGZIP(), []int{1}
}

func (x *CurrentMythicRating) GetColor() *warcraft.Color {
	if x != nil {
		return x.Color
	}
	return nil
}

func (x *CurrentMythicRating) GetRating() float32 {
	if x != nil {
		return x.Rating
	}
	return 0
}

// 📌 Mythic Keystone Profile
type KeystoneRating struct {
	state               protoimpl.MessageState        `protogen:"open.v1"`
	XLinks              *warcraft.Self                `protobuf:"bytes,1,opt,name=_links,json=Links,proto3" json:"_links,omitempty"`
	CurrentPeriod       *KeystoneRating_CurrentPeriod `protobuf:"bytes,2,opt,name=current_period,json=currentPeriod,proto3" json:"current_period,omitempty"`
	Seasons             []*PeriodRef                  `protobuf:"bytes,3,rep,name=seasons,proto3" json:"seasons,omitempty"`
	Character           *warcraft.ShortCharacter      `protobuf:"bytes,4,opt,name=character,proto3" json:"character,omitempty"`
	CurrentMythicRating *CurrentMythicRating          `protobuf:"bytes,5,opt,name=current_mythic_rating,json=currentMythicRating,proto3" json:"current_mythic_rating,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *KeystoneRating) Reset() {
	*x = KeystoneRating{}
	mi := &file_warcraft_cronjobs_cronjob_mythic_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeystoneRating) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeystoneRating) ProtoMessage() {}

func (x *KeystoneRating) ProtoReflect() protoreflect.Message {
	mi := &file_warcraft_cronjobs_cronjob_mythic_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeystoneRating.ProtoReflect.Descriptor instead.
func (*KeystoneRating) Descriptor() ([]byte, []int) {
	return file_warcraft_cronjobs_cronjob_mythic_proto_rawDescGZIP(), []int{2}
}

func (x *KeystoneRating) GetXLinks() *warcraft.Self {
	if x != nil {
		return x.XLinks
	}
	return nil
}

func (x *KeystoneRating) GetCurrentPeriod() *KeystoneRating_CurrentPeriod {
	if x != nil {
		return x.CurrentPeriod
	}
	return nil
}

func (x *KeystoneRating) GetSeasons() []*PeriodRef {
	if x != nil {
		return x.Seasons
	}
	return nil
}

func (x *KeystoneRating) GetCharacter() *warcraft.ShortCharacter {
	if x != nil {
		return x.Character
	}
	return nil
}

func (x *KeystoneRating) GetCurrentMythicRating() *CurrentMythicRating {
	if x != nil {
		return x.CurrentMythicRating
	}
	return nil
}

type KeystoneRating_CurrentPeriod struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Period        *PeriodRef             `protobuf:"bytes,1,opt,name=period,proto3" json:"period,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeystoneRating_CurrentPeriod) Reset() {
	*x = KeystoneRating_CurrentPeriod{}
	mi := &file_warcraft_cronjobs_cronjob_mythic_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeystoneRating_CurrentPeriod) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeystoneRating_CurrentPeriod) ProtoMessage() {}

func (x *KeystoneRating_CurrentPeriod) ProtoReflect() protoreflect.Message {
	mi := &file_warcraft_cronjobs_cronjob_mythic_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeystoneRating_CurrentPeriod.ProtoReflect.Descriptor instead.
func (*KeystoneRating_CurrentPeriod) Descriptor() ([]byte, []int) {
	return file_warcraft_cronjobs_cronjob_mythic_proto_rawDescGZIP(), []int{2, 0}
}

func (x *KeystoneRating_CurrentPeriod) GetPeriod() *PeriodRef {
	if x != nil {
		return x.Period
	}
	return nil
}

var File_warcraft_cronjobs_cronjob_mythic_proto protoreflect.FileDescriptor

const file_warcraft_cronjobs_cronjob_mythic_proto_rawDesc = "" +
	"\n" +
	"&warcraft/cronjobs/cronjob-mythic.proto\x12\x11warcraft.cronjobs\x1a\x15warcraft/common.proto\"<\n" +
	"\tPeriodRef\x12\x1f\n" +
	"\x03key\x18\x01 \x01(\v2\r.warcraft.KeyR\x03key\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\x03R\x02id\"T\n" +
	"\x13CurrentMythicRating\x12%\n" +
	"\x05color\x18\x01 \x01(\v2\x0f.warcraft.ColorR\x05color\x12\x16\n" +
	"\x06rating\x18\x02 \x01(\x02R\x06rating\"\xa2\x03\n" +
	"\x0eKeystoneRating\x12%\n" +
	"\x06_links\x18\x01 \x01(\v2\x0e.warcraft.SelfR\x05Links\x12V\n" +
	"\x0ecurrent_period\x18\x02 \x01(\v2/.warcraft.cronjobs.KeystoneRating.CurrentPeriodR\rcurrentPeriod\x126\n" +
	"\aseasons\x18\x03 \x03(\v2\x1c.warcraft.cronjobs.PeriodRefR\aseasons\x126\n" +
	"\tcharacter\x18\x04 \x01(\v2\x18.warcraft.ShortCharacterR\tcharacter\x12Z\n" +
	"\x15current_mythic_rating\x18\x05 \x01(\v2&.warcraft.cronjobs.CurrentMythicRatingR\x13currentMythicRating\x1aE\n" +
	"\rCurrentPeriod\x124\n" +
	"\x06period\x18\x01 \x01(\v2\x1c.warcraft.cronjobs.PeriodRefR\x06periodBHZFgithub.com/ToxicToast/Azkaban-Go/libs/proto/warcraft/cronjobs;cronjobsb\x06proto3"

var (
	file_warcraft_cronjobs_cronjob_mythic_proto_rawDescOnce sync.Once
	file_warcraft_cronjobs_cronjob_mythic_proto_rawDescData []byte
)

func file_warcraft_cronjobs_cronjob_mythic_proto_rawDescGZIP() []byte {
	file_warcraft_cronjobs_cronjob_mythic_proto_rawDescOnce.Do(func() {
		file_warcraft_cronjobs_cronjob_mythic_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_warcraft_cronjobs_cronjob_mythic_proto_rawDesc), len(file_warcraft_cronjobs_cronjob_mythic_proto_rawDesc)))
	})
	return file_warcraft_cronjobs_cronjob_mythic_proto_rawDescData
}

var file_warcraft_cronjobs_cronjob_mythic_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_warcraft_cronjobs_cronjob_mythic_proto_goTypes = []any{
	(*PeriodRef)(nil),                    // 0: warcraft.cronjobs.PeriodRef
	(*CurrentMythicRating)(nil),          // 1: warcraft.cronjobs.CurrentMythicRating
	(*KeystoneRating)(nil),               // 2: warcraft.cronjobs.KeystoneRating
	(*KeystoneRating_CurrentPeriod)(nil), // 3: warcraft.cronjobs.KeystoneRating.CurrentPeriod
	(*warcraft.Key)(nil),                 // 4: warcraft.Key
	(*warcraft.Color)(nil),               // 5: warcraft.Color
	(*warcraft.Self)(nil),                // 6: warcraft.Self
	(*warcraft.ShortCharacter)(nil),      // 7: warcraft.ShortCharacter
}
var file_warcraft_cronjobs_cronjob_mythic_proto_depIdxs = []int32{
	4, // 0: warcraft.cronjobs.PeriodRef.key:type_name -> warcraft.Key
	5, // 1: warcraft.cronjobs.CurrentMythicRating.color:type_name -> warcraft.Color
	6, // 2: warcraft.cronjobs.KeystoneRating._links:type_name -> warcraft.Self
	3, // 3: warcraft.cronjobs.KeystoneRating.current_period:type_name -> warcraft.cronjobs.KeystoneRating.CurrentPeriod
	0, // 4: warcraft.cronjobs.KeystoneRating.seasons:type_name -> warcraft.cronjobs.PeriodRef
	7, // 5: warcraft.cronjobs.KeystoneRating.character:type_name -> warcraft.ShortCharacter
	1, // 6: warcraft.cronjobs.KeystoneRating.current_mythic_rating:type_name -> warcraft.cronjobs.CurrentMythicRating
	0, // 7: warcraft.cronjobs.KeystoneRating.CurrentPeriod.period:type_name -> warcraft.cronjobs.PeriodRef
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_warcraft_cronjobs_cronjob_mythic_proto_init() }
func file_warcraft_cronjobs_cronjob_mythic_proto_init() {
	if File_warcraft_cronjobs_cronjob_mythic_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_warcraft_cronjobs_cronjob_mythic_proto_rawDesc), len(file_warcraft_cronjobs_cronjob_mythic_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_warcraft_cronjobs_cronjob_mythic_proto_goTypes,
		DependencyIndexes: file_warcraft_cronjobs_cronjob_mythic_proto_depIdxs,
		MessageInfos:      file_warcraft_cronjobs_cronjob_mythic_proto_msgTypes,
	}.Build()
	File_warcraft_cronjobs_cronjob_mythic_proto = out.File
	file_warcraft_cronjobs_cronjob_mythic_proto_goTypes = nil
	file_warcraft_cronjobs_cronjob_mythic_proto_depIdxs = nil
}
