// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: warcraft/cronjobs/cronjob-search.proto

package cronjobs

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Search struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Region        string                 `protobuf:"bytes,1,opt,name=region,proto3" json:"region,omitempty"`
	Realm         string                 `protobuf:"bytes,2,opt,name=realm,proto3" json:"realm,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Namespace     string                 `protobuf:"bytes,4,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Locale        string                 `protobuf:"bytes,5,opt,name=locale,proto3" json:"locale,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Search) Reset() {
	*x = Search{}
	mi := &file_warcraft_cronjobs_cronjob_search_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Search) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Search) ProtoMessage() {}

func (x *Search) ProtoReflect() protoreflect.Message {
	mi := &file_warcraft_cronjobs_cronjob_search_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Search.ProtoReflect.Descriptor instead.
func (*Search) Descriptor() ([]byte, []int) {
	return file_warcraft_cronjobs_cronjob_search_proto_rawDescGZIP(), []int{0}
}

func (x *Search) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *Search) GetRealm() string {
	if x != nil {
		return x.Realm
	}
	return ""
}

func (x *Search) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Search) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *Search) GetLocale() string {
	if x != nil {
		return x.Locale
	}
	return ""
}

var File_warcraft_cronjobs_cronjob_search_proto protoreflect.FileDescriptor

const file_warcraft_cronjobs_cronjob_search_proto_rawDesc = "" +
	"\n" +
	"&warcraft/cronjobs/cronjob-search.proto\x12\x11warcraft.cronjobs\"\x80\x01\n" +
	"\x06Search\x12\x16\n" +
	"\x06region\x18\x01 \x01(\tR\x06region\x12\x14\n" +
	"\x05realm\x18\x02 \x01(\tR\x05realm\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x1c\n" +
	"\tnamespace\x18\x04 \x01(\tR\tnamespace\x12\x16\n" +
	"\x06locale\x18\x05 \x01(\tR\x06localeBHZFgithub.com/ToxicToast/Azkaban-Go/libs/proto/warcraft/cronjobs;cronjobsb\x06proto3"

var (
	file_warcraft_cronjobs_cronjob_search_proto_rawDescOnce sync.Once
	file_warcraft_cronjobs_cronjob_search_proto_rawDescData []byte
)

func file_warcraft_cronjobs_cronjob_search_proto_rawDescGZIP() []byte {
	file_warcraft_cronjobs_cronjob_search_proto_rawDescOnce.Do(func() {
		file_warcraft_cronjobs_cronjob_search_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_warcraft_cronjobs_cronjob_search_proto_rawDesc), len(file_warcraft_cronjobs_cronjob_search_proto_rawDesc)))
	})
	return file_warcraft_cronjobs_cronjob_search_proto_rawDescData
}

var file_warcraft_cronjobs_cronjob_search_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_warcraft_cronjobs_cronjob_search_proto_goTypes = []any{
	(*Search)(nil), // 0: warcraft.cronjobs.Search
}
var file_warcraft_cronjobs_cronjob_search_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_warcraft_cronjobs_cronjob_search_proto_init() }
func file_warcraft_cronjobs_cronjob_search_proto_init() {
	if File_warcraft_cronjobs_cronjob_search_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_warcraft_cronjobs_cronjob_search_proto_rawDesc), len(file_warcraft_cronjobs_cronjob_search_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_warcraft_cronjobs_cronjob_search_proto_goTypes,
		DependencyIndexes: file_warcraft_cronjobs_cronjob_search_proto_depIdxs,
		MessageInfos:      file_warcraft_cronjobs_cronjob_search_proto_msgTypes,
	}.Build()
	File_warcraft_cronjobs_cronjob_search_proto = out.File
	file_warcraft_cronjobs_cronjob_search_proto_goTypes = nil
	file_warcraft_cronjobs_cronjob_search_proto_depIdxs = nil
}
