// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: warcraft/character.proto

package warcraft

import (
	common "github.com/ToxicToast/Azkaban-Go/libs/proto/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_warcraft_character_proto protoreflect.FileDescriptor

const file_warcraft_character_proto_rawDesc = "" +
	"\n" +
	"\x18warcraft/character.proto\x12\bwarcraft\x1a\x13common/common.proto\x1a\x1dwarcraft/character-type.proto\x1a\"warcraft/character-responses.proto\x1a!warcraft/character-requests.proto2\xc5\x04\n" +
	"\x18WarcraftCharacterService\x12E\n" +
	"\rGetCharacters\x12\x13.common.ListRequest\x1a\x1f.warcraft.GetCharactersResponse\x12=\n" +
	"\x11GetCharactersById\x12\x13.common.ByIdRequest\x1a\x13.warcraft.Character\x12]\n" +
	"\x1aGetCharactersByCharacterId\x12*.warcraft.GetCharacterByCharacterIdRequest\x1a\x13.warcraft.Character\x12Q\n" +
	"\x15GetCharactersByUserId\x12\x17.common.ByUserIdRequest\x1a\x1f.warcraft.GetCharactersResponse\x12]\n" +
	"\x14GetCharactersByGuild\x12$.warcraft.GetCharacterByGuildRequest\x1a\x1f.warcraft.GetCharactersResponse\x12H\n" +
	"\x0fCreateCharacter\x12 .warcraft.CreateCharacterRequest\x1a\x13.warcraft.Character\x12H\n" +
	"\x0fAssignCharacter\x12 .warcraft.AssignCharacterRequest\x1a\x13.warcraft.CharacterB?Z=github.com/ToxicToast/Azkaban-Go/libs/proto/warcraft;warcraftb\x06proto3"

var file_warcraft_character_proto_goTypes = []any{
	(*common.ListRequest)(nil),               // 0: common.ListRequest
	(*common.ByIdRequest)(nil),               // 1: common.ByIdRequest
	(*GetCharacterByCharacterIdRequest)(nil), // 2: warcraft.GetCharacterByCharacterIdRequest
	(*common.ByUserIdRequest)(nil),           // 3: common.ByUserIdRequest
	(*GetCharacterByGuildRequest)(nil),       // 4: warcraft.GetCharacterByGuildRequest
	(*CreateCharacterRequest)(nil),           // 5: warcraft.CreateCharacterRequest
	(*AssignCharacterRequest)(nil),           // 6: warcraft.AssignCharacterRequest
	(*GetCharactersResponse)(nil),            // 7: warcraft.GetCharactersResponse
	(*Character)(nil),                        // 8: warcraft.Character
}
var file_warcraft_character_proto_depIdxs = []int32{
	0, // 0: warcraft.WarcraftCharacterService.GetCharacters:input_type -> common.ListRequest
	1, // 1: warcraft.WarcraftCharacterService.GetCharactersById:input_type -> common.ByIdRequest
	2, // 2: warcraft.WarcraftCharacterService.GetCharactersByCharacterId:input_type -> warcraft.GetCharacterByCharacterIdRequest
	3, // 3: warcraft.WarcraftCharacterService.GetCharactersByUserId:input_type -> common.ByUserIdRequest
	4, // 4: warcraft.WarcraftCharacterService.GetCharactersByGuild:input_type -> warcraft.GetCharacterByGuildRequest
	5, // 5: warcraft.WarcraftCharacterService.CreateCharacter:input_type -> warcraft.CreateCharacterRequest
	6, // 6: warcraft.WarcraftCharacterService.AssignCharacter:input_type -> warcraft.AssignCharacterRequest
	7, // 7: warcraft.WarcraftCharacterService.GetCharacters:output_type -> warcraft.GetCharactersResponse
	8, // 8: warcraft.WarcraftCharacterService.GetCharactersById:output_type -> warcraft.Character
	8, // 9: warcraft.WarcraftCharacterService.GetCharactersByCharacterId:output_type -> warcraft.Character
	7, // 10: warcraft.WarcraftCharacterService.GetCharactersByUserId:output_type -> warcraft.GetCharactersResponse
	7, // 11: warcraft.WarcraftCharacterService.GetCharactersByGuild:output_type -> warcraft.GetCharactersResponse
	8, // 12: warcraft.WarcraftCharacterService.CreateCharacter:output_type -> warcraft.Character
	8, // 13: warcraft.WarcraftCharacterService.AssignCharacter:output_type -> warcraft.Character
	7, // [7:14] is the sub-list for method output_type
	0, // [0:7] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_warcraft_character_proto_init() }
func file_warcraft_character_proto_init() {
	if File_warcraft_character_proto != nil {
		return
	}
	file_warcraft_character_type_proto_init()
	file_warcraft_character_responses_proto_init()
	file_warcraft_character_requests_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_warcraft_character_proto_rawDesc), len(file_warcraft_character_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_warcraft_character_proto_goTypes,
		DependencyIndexes: file_warcraft_character_proto_depIdxs,
	}.Build()
	File_warcraft_character_proto = out.File
	file_warcraft_character_proto_goTypes = nil
	file_warcraft_character_proto_depIdxs = nil
}
