// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: warcraft/cronjob.proto

package warcraft

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_warcraft_cronjob_proto protoreflect.FileDescriptor

const file_warcraft_cronjob_proto_rawDesc = "" +
	"\n" +
	"\x16warcraft/cronjob.proto\x12\bwarcraft\x1a\x1dwarcraft/cronjob-search.proto\x1a(warcraft/cronjob-character-profile.proto\x1a\x1cwarcraft/cronjob-guild.proto\x1a#warcraft/cronjob-guild-roster.proto\x1a\x1cwarcraft/cronjob-media.proto\x1a\x1dwarcraft/cronjob-mythic.proto2\xb6\x02\n" +
	"\x16WarcraftCronjobService\x126\n" +
	"\x0fSearchCharacter\x12\x10.warcraft.Search\x1a\x11.warcraft.Profile\x120\n" +
	"\vSearchMedia\x12\x10.warcraft.Search\x1a\x0f.warcraft.Media\x12B\n" +
	"\x14SearchKeystoneRating\x12\x10.warcraft.Search\x1a\x18.warcraft.KeystoneRating\x120\n" +
	"\vSearchGuild\x12\x10.warcraft.Search\x1a\x0f.warcraft.Guild\x12<\n" +
	"\x11SearchGuildRoster\x12\x10.warcraft.Search\x1a\x15.warcraft.GuildRosterB?Z=github.com/ToxicToast/Azkaban-Go/libs/proto/warcraft;warcraftb\x06proto3"

var file_warcraft_cronjob_proto_goTypes = []any{
	(*Search)(nil),         // 0: warcraft.Search
	(*Profile)(nil),        // 1: warcraft.Profile
	(*Media)(nil),          // 2: warcraft.Media
	(*KeystoneRating)(nil), // 3: warcraft.KeystoneRating
	(*Guild)(nil),          // 4: warcraft.Guild
	(*GuildRoster)(nil),    // 5: warcraft.GuildRoster
}
var file_warcraft_cronjob_proto_depIdxs = []int32{
	0, // 0: warcraft.WarcraftCronjobService.SearchCharacter:input_type -> warcraft.Search
	0, // 1: warcraft.WarcraftCronjobService.SearchMedia:input_type -> warcraft.Search
	0, // 2: warcraft.WarcraftCronjobService.SearchKeystoneRating:input_type -> warcraft.Search
	0, // 3: warcraft.WarcraftCronjobService.SearchGuild:input_type -> warcraft.Search
	0, // 4: warcraft.WarcraftCronjobService.SearchGuildRoster:input_type -> warcraft.Search
	1, // 5: warcraft.WarcraftCronjobService.SearchCharacter:output_type -> warcraft.Profile
	2, // 6: warcraft.WarcraftCronjobService.SearchMedia:output_type -> warcraft.Media
	3, // 7: warcraft.WarcraftCronjobService.SearchKeystoneRating:output_type -> warcraft.KeystoneRating
	4, // 8: warcraft.WarcraftCronjobService.SearchGuild:output_type -> warcraft.Guild
	5, // 9: warcraft.WarcraftCronjobService.SearchGuildRoster:output_type -> warcraft.GuildRoster
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_warcraft_cronjob_proto_init() }
func file_warcraft_cronjob_proto_init() {
	if File_warcraft_cronjob_proto != nil {
		return
	}
	file_warcraft_cronjob_search_proto_init()
	file_warcraft_cronjob_character_profile_proto_init()
	file_warcraft_cronjob_guild_proto_init()
	file_warcraft_cronjob_guild_roster_proto_init()
	file_warcraft_cronjob_media_proto_init()
	file_warcraft_cronjob_mythic_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_warcraft_cronjob_proto_rawDesc), len(file_warcraft_cronjob_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_warcraft_cronjob_proto_goTypes,
		DependencyIndexes: file_warcraft_cronjob_proto_depIdxs,
	}.Build()
	File_warcraft_cronjob_proto = out.File
	file_warcraft_cronjob_proto_goTypes = nil
	file_warcraft_cronjob_proto_depIdxs = nil
}
