// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: warcraft/guild.proto

package warcraft

import (
	common "github.com/ToxicToast/Azkaban-Go/libs/proto/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_warcraft_guild_proto protoreflect.FileDescriptor

const file_warcraft_guild_proto_rawDesc = "" +
	"\n" +
	"\x14warcraft/guild.proto\x12\bwarcraft\x1a\x13common/common.proto\x1a\x1ewarcraft/guild-responses.proto2U\n" +
	"\x14WarcraftGuildService\x12=\n" +
	"\tGetGuilds\x12\x13.common.ListRequest\x1a\x1b.warcraft.GetGuildsResponseB?Z=github.com/ToxicToast/Azkaban-Go/libs/proto/warcraft;warcraftb\x06proto3"

var file_warcraft_guild_proto_goTypes = []any{
	(*common.ListRequest)(nil), // 0: common.ListRequest
	(*GetGuildsResponse)(nil),  // 1: warcraft.GetGuildsResponse
}
var file_warcraft_guild_proto_depIdxs = []int32{
	0, // 0: warcraft.WarcraftGuildService.GetGuilds:input_type -> common.ListRequest
	1, // 1: warcraft.WarcraftGuildService.GetGuilds:output_type -> warcraft.GetGuildsResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_warcraft_guild_proto_init() }
func file_warcraft_guild_proto_init() {
	if File_warcraft_guild_proto != nil {
		return
	}
	file_warcraft_guild_responses_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_warcraft_guild_proto_rawDesc), len(file_warcraft_guild_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_warcraft_guild_proto_goTypes,
		DependencyIndexes: file_warcraft_guild_proto_depIdxs,
	}.Build()
	File_warcraft_guild_proto = out.File
	file_warcraft_guild_proto_goTypes = nil
	file_warcraft_guild_proto_depIdxs = nil
}
